add aegis

diff --git a/aegis b/aegis
--- a/aegis
+++ b/aegis
@@ -1,13 +1,13 @@
 #! /bin/bash
 
 ### BEGIN INIT INFO
-# Provides:          ssserver
+# Provides:          aegis
 # Required-Start:    $local_fs $network $named $remote_fs $syslog
 # Required-Stop:     $local_fs $network $named $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: sinosky shadowsocks server daemon
-# Description:       A tunnel proxy which help you get through firewalls.
+# Short-Description: aliyun aegis
+# Description:       A security and defense service by alibaba.
 ### END INIT INFO
 
 PATH=~/sbin:/usr/local/sbin:/usr/sbin:/sbin:~/bin:/usr/local/bin:/usr/bin:/bin
@@ -21,29 +21,25 @@ fi
 ###############################################################
 ########## Maybe you need to modify these variables. ##########
 
-name=ssserver
+name=aegis
 
-### shadowsocks need python 2 or node.js to run it.
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
-### Try using `which $name` to find the full path, or just use `$name` if the binary file is in `$PATH`.
-bin=/usr/local/bin/$name
+### Try using `which $name` to find the full path, or just use `$name` if it is in `$PATH`.
+bin=/usr/local/aegis/aegis_update/aegis_update
 if [ ! -x "$bin" ]; then
     echo -e "\033[1;31m[E]\033[0m  Can not find $bin, maybe the program isn't installed." >&2
     exit 5
 fi
 
 ### In the most cases, the configuration file of programs are in `/etc`. You can create your own configuration file and edit this variable to the new path.
-config=/home/www/etc/shadowsocks.json
+config=/usr/local/aegis/aegis_update/agx_update.cfg
 if [ ! -r "$config" ]; then
     echo -e "\033[1;31m[E]\033[0m  The configuration file isn't found, maybe the path ($config) is wrong." >&2
     exit 6
 fi
 
-### In the most cases, the log file of programs are in `/var/log`. You are free to modify this variable.
-log=/home/www/log/shadowsocks.log
-
-### By default, the pid file of programs are in `/var/run`. So you don't need to modify this variable.
-pidFile=/var/run/$name.pid
+### By default, the pid file of programs are in `/var/run`. So you don't need to edit this variable.
+pidFile=/usr/local/aegis/aegis_update/pid.txt
 
 ##########                                           ##########
 ###############################################################
@@ -51,26 +47,25 @@ pidFile=/var/run/$name.pid
 script=$(basename "$0")
 
 getPid() {
-    ### Delete spaces, tabs and newlines.
     pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
     ### `$pidFile` may be blank. If the process exists, `! kill -0 $pid 2>/dev/null` will return 1.
     if [ -z "$pid" ] || ! kill -0 $pid 2>/dev/null; then
         rm -f $pidFile
-        unset pid
+        unset pid cliPid
     fi
 }
 
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
-    if nohup $bin -c "$config" >> "$log" 2>&1 & then
+    if $bin -f $config; then
         echo -n '.'
-        pid=$!
-        echo -n $pid > $pidFile
+        sleep 1
     else
         echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
         exit 1
     fi
 
+    getPid
     ### Successfully start the program if the process exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
         if kill -0 $pid 2>/dev/null; then
@@ -85,13 +80,12 @@ doStart() {
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
-
 doStop() {
     echo -en "\033[1;36m[I]\033[0m  Stopping $name"
-    if kill $pid; then
+    if kill -2 $pid 2>/dev/null; then
         echo -n '.'
     else
-        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error."
         exit 1
     fi
 
@@ -109,7 +103,7 @@ doStop() {
         fi
     done
 
-    echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
+    echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed."
     exit 1
 }
 
@@ -127,23 +121,6 @@ case "$1" in
     getPid
     if [ "$pid" ]; then
         doStop
-    else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
-    fi
-    ;;
-
-    kill)
-    getPid
-    if [ "$pid" ]; then
-        echo -e "\033[1;36m[I]\033[0m  Forcefully killing the process of $name..."
-
-        if kill -9 $pid; then
-            rm -f $pidFile
-            echo -e "\033[1;32m[N]\033[0m  Kill $name done."
-        else
-            echo -e "\033[1;31m[E]\033[0m  Kill $name error."
-            exit 1
-        fi
     else
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
     fi
@@ -184,7 +161,7 @@ case "$1" in
     ;;
 
     *)
-    echo "Usage: [sudo] $script {start|stop|kill|restart|force-reload|status}." >&2
+    echo "Usage: [sudo] $script {start|stop|restart|force-reload|status}." >&2
     exit 3
     ;;
 esac
diff --git a/aria2c b/aria2c
--- a/aria2c
+++ b/aria2c
@@ -88,7 +88,7 @@ doStart() {
         pid=$(pgrep -f $bin)
         echo -n $pid > $pidFile
     else
-        echo -e "\n\033[1;31m[E]\033[0m  Start $name error." >&2
+        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
         exit 1
     fi
 
@@ -99,7 +99,7 @@ doStart() {
             sleep 1
         else
             rm -f $pidFile
-            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed." >&2
+            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
             exit 1
         fi
     done
@@ -111,17 +111,13 @@ doStop() {
     if kill $pid; then
         echo -n '.'
     else
-        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill." >&2
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
         exit 1
     fi
 
     ### Successfully stop the program if the process doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
-            if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill." >&2
-                exit 1
-            fi
             echo -n '.'
             sleep 1
         else
@@ -129,16 +125,19 @@ doStop() {
             ### Just for restart.
             unset pid
             echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
-            break
+            return 0
         fi
     done
+
+    echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
+    exit 1
 }
 
 case "$1" in
     start)
     getPid
     if [ "$pid" ]; then
-        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid" >&2
+        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid"
     else
         doStart
     fi
@@ -149,7 +148,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running." >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
     fi
     ;;
 
@@ -162,11 +161,11 @@ case "$1" in
             rm -f $pidFile
             echo -e "\033[1;32m[N]\033[0m  Kill $name done."
         else
-            echo -e "\033[1;31m[E]\033[0m  Kill $name error." >&2
+            echo -e "\033[1;31m[E]\033[0m  Kill $name error."
             exit 1
         fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running." >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
     fi
     ;;
 
@@ -177,7 +176,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running" >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -189,7 +188,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running" >&2
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
         exit 7
     fi
     ;;
diff --git a/cmsd b/cmsd
--- a/cmsd
+++ b/cmsd
@@ -6,7 +6,7 @@
 # Required-Stop:     $local_fs $network $named $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: aliyun jiankong agent
+# Short-Description: aliyun monitor agent
 # Description:       A server monitor by alibaba.
 ### END INIT INFO
 
@@ -72,17 +72,19 @@ doStart() {
         exit 1
     fi
 
-    until [ "$pid1" ] && [ "$pid2" ]; do
+    until [ "$pid2" ]; do
         pids=$(pgrep -f $bin)
-        if [ -z "$pids" ]; then
+        if [ "$pids" ]; then
+            pid1=$(echo $pids | awk '{print $1}')
+            pid2=$(echo $pids | awk '{print $2}')
+
+            echo -n '.'
+            sleep 1
+        else
             echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
             exit 1
         fi
-        pid1=$(echo $pids | awk '{print $1}')
-        pid2=$(echo $pids | awk '{print $2}')
 
-        echo -n '.'
-        sleep 1
     done
 
     echo -n $pids > $pidFile
@@ -102,10 +104,6 @@ doStop() {
     ### Successfully stop the program if the process doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid1 2>/dev/null || kill -0 $pid2 2>/dev/null; then
-            if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed."
-                exit 1
-            fi
             echo -n '.'
             sleep 1
         else
@@ -113,16 +111,19 @@ doStop() {
             ### Just for restart.
             unset pid1 pid2
             echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
-            break
+            return 0
         fi
     done
+
+    echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed."
+    exit 1
 }
 
 case "$1" in
     start)
     getPid
     if [ "$pid1" ] && [ "$pid2" ]; then
-        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid1 = $pid1, pid2 = $pid2." >&2
+        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid1 = $pid1, pid2 = $pid2."
     else
         doStart
     fi
@@ -133,7 +134,7 @@ case "$1" in
     if [ "$pid1" ] && [ "$pid2" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running." >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
     fi
     ;;
 
@@ -144,19 +145,19 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running" >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
 
     force-reload)
     getPid
-    if [ "$pid" ]; then
+    if [ "$pid1" ] && [ "$pid2" ]; then
         echo -e "\033[1;36m[I]\033[0m  Forcefully reloading (restarting) $name:"
         doStop
         doStart
     else
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running" >&2
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
         exit 7
     fi
     ;;
diff --git a/mysqld b/mysqld
--- a/mysqld
+++ b/mysqld
@@ -62,22 +62,17 @@ doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
     ### mysqld_safe is a script for running mysqld, so we can't use its pid.
     if $bin --defaults-file="$config" > /dev/null 2>&1 & then
+        scriptPid=$!
         echo -n '.'
     else
         echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
         exit 1
     fi
 
-    ### Wait for mysqld start. Try waiting for a longer time if start mysqld failed.
-    for (( i=0; i<=3; i++ )); do
-        echo -n '.'
-        sleep 1
-    done
+    until [ "$pid" ]; do
+        if kill -0 $scriptPid 2>/dev/null; then
+            pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
 
-    getPid
-    ### Successfully start the program if the process exists after 5 seconds.
-    for (( i=0; i<=5; i++ )); do
-        if kill -0 $pid 2>/dev/null; then
             echo -n '.'
             sleep 1
         else
@@ -85,6 +80,7 @@ doStart() {
             exit 1
         fi
     done
+
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
@@ -100,26 +96,25 @@ doStop() {
     ### Successfully stop the program if the process doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
-            if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed."
-                exit 1
-            fi
             echo -n '.'
             sleep 1
         else
             ### Just for restart.
             unset pid
             echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
-            break
+            return 0
         fi
     done
+
+    echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed."
+    exit 1
 }
 
 case "$1" in
     start)
     getPid
     if [ "$pid" ]; then
-        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid" >&2
+        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid"
     else
         doStart
     fi
@@ -130,7 +125,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running." >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
     fi
     ;;
 
@@ -141,7 +136,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running" >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -153,7 +148,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running" >&2
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
         exit 7
     fi
     ;;
diff --git a/redis-server b/redis-server
--- a/redis-server
+++ b/redis-server
@@ -25,8 +25,8 @@ name=redis
 
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
 ### Try using `which redis-server` and `which redis-cli` to find the full path, or just use `redis-server` and `redis-cli` if it is in `$PATH`.
-bin=/usr/local/redis/bin/redis-server
-cliBin=/usr/local/redis/bin/redis-cli
+bin=/usr/bin/redis-server
+cliBin=/usr/bin/redis-cli
 if [ ! -x "$bin" ] || [ ! -x "$cliBin" ] ; then
     echo -e "\033[1;31m[E]\033[0m  Can not find $bin or $cliBin, maybe the program isn't installed." >&2
     exit 5
@@ -64,16 +64,11 @@ doStart() {
     ### So you need to create them manually, and change owner & group. You can find the paths in the configuration file.
     if su redis -s /bin/bash -c "$bin '$config'" 2>/dev/null; then
         echo -n '.'
+        sleep 1
     else
         echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
         exit 1
     fi
-
-    ### Wait for redis-server start. Try waiting for a longer time if start redis-server failed.
-    for (( i=0; i<=1; i++ )); do
-        echo -n '.'
-        sleep 1
-    done
 
     getPid
     ### Successfully start the program if the process exists after 5 seconds.
@@ -101,26 +96,25 @@ doStop() {
     ### Successfully stop the program if the process doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
-            if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed."
-                exit 1
-            fi
             echo -n '.'
             sleep 1
         else
             ### Just for restart.
             unset pid
             echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
-            break
+            return 0
         fi
     done
+
+    echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed."
+    exit 1
 }
 
 case "$1" in
     start)
     getPid
     if [ "$pid" ]; then
-        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid" >&2
+        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid"
     else
         doStart
     fi
@@ -131,7 +125,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running." >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
     fi
     ;;
 
@@ -142,7 +136,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running" >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -154,7 +148,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running" >&2
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
         exit 7
     fi
     ;;
diff --git a/rsyncd b/rsyncd
--- a/rsyncd
+++ b/rsyncd
@@ -94,26 +94,25 @@ doStop() {
     ### Successfully stop the program if the process doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
-            if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
-                exit 1
-            fi
             echo -n '.'
             sleep 1
         else
             ### Just for restart.
             unset pid
             echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
-            break
+            return 0
         fi
     done
+
+    echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
+    exit 1
 }
 
 case "$1" in
     start)
     getPid
     if [ "$pid" ]; then
-        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid" >&2
+        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid"
     else
         doStart
     fi
@@ -124,7 +123,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running." >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
     fi
     ;;
 
@@ -141,7 +140,7 @@ case "$1" in
             exit 1
         fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running." >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
     fi
     ;;
 
@@ -152,7 +151,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running" >&2
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -164,7 +163,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running" >&2
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
         exit 7
     fi
     ;;
