update

diff --git a/aria2c b/aria2c
--- a/aria2c
+++ b/aria2c
@@ -10,7 +10,7 @@
 # Description:       aria2 is a lightweight multi-protocol & multi-source command-line download utility.
 ### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:~/bin
+PATH=~/sbin:/usr/local/sbin:/usr/sbin:/sbin:~/bin:/usr/local/bin:/usr/bin:/bin
 export PATH
 
 if [ "$(id -u)" != "0" ]; then
@@ -18,17 +18,34 @@ if [ "$(id -u)" != "0" ]; then
     exit 4
 fi
 
-### Maybe you need to modify these variables.
+###############################################################
+########## Maybe you need to modify these variables. ##########
+
 name=aria2c
+
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
-### Try use `which $name` to find the full path, or just use `$name` if the binary file is in `$PATH`.
+### Try using `which $name` to find the full path, or just use `$name` if the binary file is in `$PATH`.
 bin=/usr/bin/$name
+if [ ! -x "$bin" ]; then
+    echo -e "\033[1;31m[E]\033[0m  Can not find $bin, maybe the program isn't installed." >&2
+    exit 5
+fi
+
 ### In the most cases, the configuration file of programs are in `/etc`. You can create your own configuration file and edit this variable to the new path.
 config=/etc/aria2.conf
+if [ ! -r "$config" ]; then
+    echo -e "\033[1;31m[E]\033[0m  The configuration file isn't found, maybe the path ($config) is wrong." >&2
+    exit 6
+fi
+
 ### In the most cases, the log file of programs are in `/var/log`. You can find the path in the configuration file.
 log=/var/log/aria2.log
+
 ### By default, the pid file of programs are in `/var/run`. So you don't need to edit this variable.
 pidFile=/var/run/$name.pid
+
+##########                                           ##########
+###############################################################
 
 script=$(basename "$0")
 
@@ -36,7 +53,7 @@ getPid() {
     ### Delete spaces, tabs and newlines.
     pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
     ### `$pidFile` may be blank. If the process exists, `! kill -0 $pid 2>/dev/null` will return 1.
-    if [ ! "$pid" ] || ! kill -0 $pid 2>/dev/null; then
+    if [ -z "$pid" ] || ! kill -0 $pid 2>/dev/null; then
         rm -f $pidFile
         unset pid
     fi
@@ -51,12 +68,11 @@ checkDlDir() {
     if [ ! -d "$dlDir" ]; then
         mkdir -p "$dlDir"
     fi
-    if [ ! -f "$sessionFile" ]; then
+    if [ ! -w "$sessionFile" ]; then
         touch "$sessionFile"
     fi
     chown -R pi:pi "$dlDir"
-
-    if [ ! -f "$log" ]; then
+    if [ ! -w "$log" ]; then
         touch "$log"
         chown pi:pi "$log"
     fi
@@ -72,7 +88,7 @@ doStart() {
         pid=$(pgrep -f $bin)
         echo -n $pid > $pidFile
     else
-        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
+        echo -e "\n\033[1;31m[E]\033[0m  Start $name error." >&2
         exit 1
     fi
 
@@ -83,7 +99,7 @@ doStart() {
             sleep 1
         else
             rm -f $pidFile
-            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
+            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed." >&2
             exit 1
         fi
     done
@@ -95,7 +111,7 @@ doStop() {
     if kill $pid; then
         echo -n '.'
     else
-        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill." >&2
         exit 1
     fi
 
@@ -103,7 +119,7 @@ doStop() {
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill." >&2
                 exit 1
             fi
             echo -n '.'
@@ -122,7 +138,7 @@ case "$1" in
     start)
     getPid
     if [ "$pid" ]; then
-        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid"
+        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid" >&2
     else
         doStart
     fi
@@ -133,7 +149,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running." >&2
     fi
     ;;
 
@@ -146,23 +162,35 @@ case "$1" in
             rm -f $pidFile
             echo -e "\033[1;32m[N]\033[0m  Kill $name done."
         else
-            echo -e "\033[1;31m[E]\033[0m  Kill $name error."
+            echo -e "\033[1;31m[E]\033[0m  Kill $name error." >&2
             exit 1
         fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running." >&2
     fi
     ;;
 
     restart)
     getPid
     if [ "$pid" ]; then
-        echo -e "\033[1;36m[I]\033[0m  Restarting $name: "
+        echo -e "\033[1;36m[I]\033[0m  Restarting $name:"
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running" >&2
         doStart
+    fi
+    ;;
+
+    force-reload)
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;36m[I]\033[0m  Forcefully reloading (restarting) $name:"
+        doStop
+        doStart
+    else
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running" >&2
+        exit 7
     fi
     ;;
 
@@ -177,7 +205,7 @@ case "$1" in
     ;;
 
     *)
-    echo "Usage: [sudo] $script {start|stop|kill|restart|status}." >&2
+    echo "Usage: [sudo] $script {start|stop|kill|restart|force-reload|force-reload|status}." >&2
     exit 3
     ;;
 esac
