update

diff --git a/aria2c b/aria2c
--- a/aria2c
+++ b/aria2c
@@ -20,7 +20,7 @@ if [ "$(id -u)" != "0" ]; then
     exit 3
 fi
 
-### Maybe you need to change these.
+### Maybe you need to modify these.
 name=aria2c
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
 ### Try use `which $name` to find the full path, or just use `$name` if the binary file is in `$PATH`.
@@ -32,6 +32,8 @@ log=/var/log/aria2.log
 ### By default, the pid file of programs are in `/var/run`. So you don't need to edit this.
 pidFile=/var/run/$name.pid
 
+script=$(basename "$0")
+
 getPid() {
     ### Delete spaces, tabs and newlines.
     pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
@@ -42,31 +44,41 @@ getPid() {
     fi
 }
 
-### Change these for your own path.
+### Modify these to your own path.
 dlDir=/media/Files/Downloads
 sessionFile=$dlDir/aria2.session
 
+### Modify 'pi' to your own username.
 checkDlDir() {
     if [ ! -d "$dlDir" ]; then
         mkdir "$dlDir"
+        chown pi:pi "$dlDir"
     fi
     if [ ! -f "$sessionFile" ]; then
         touch "$sessionFile"
+        chown pi:pi "$sessionFile"
     fi
     if [ ! -f "$log" ]; then
         touch "$log"
+        chown pi:pi "$log"
     fi
 }
 
-### Successfully start the application if the progress exists after 5 seconds.
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
     ### aria2 doesn't create these file automatically, so we need create it manually.
     checkDlDir
-    ### I can't use `$!` to get the pid, and aria2 doesn't create the pid file too.
-    $bin --conf-path="$config" && pidof $bin > $pidFile
+    ### I don't want it run as root. aria2 doesn't create a pid file.
+    if su pi -s /bin/bash -c "$bin --conf-path='$config'"; then
+        echo -n '.'
+        pid=$(pgrep -f $bin)
+        echo -n $pid > $pidFile
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
+        exit 1
+    fi
 
-    getPid
+    ### Successfully start the application if the progress exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             echo -n '.'
@@ -80,15 +92,20 @@ doStart() {
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
-### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
     echo -en "\033[1;36m[I]\033[0m  Stopping $name"
-    kill $pid
+    if kill $pid; then
+        echo -n '.'
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
+        exit 1
+    fi
 
+    ### Successfully stop the application if the progress doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
                 exit 1
             fi
             echo -n '.'
@@ -164,7 +181,6 @@ case "$1" in
     ;;
 
     *)
-    script=$(basename "$0")
     echo "Usage: [sudo] $script {start|stop|kill|restart|status}." >&2
     exit 3
     ;;
diff --git a/httpd b/httpd
--- a/httpd
+++ b/httpd
@@ -20,7 +20,7 @@ if [ "$(id -u)" != "0" ]; then
     exit 3
 fi
 
-### Maybe you need to change these.
+### Maybe you need to modify these.
 name=httpd
 ### The recommended method of invoking the httpd executable is to use the apachectl control script.
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
@@ -31,6 +31,8 @@ config=/home/www/etc/apache/$name.conf
 ### By default, the pid file of programs are in `/var/run`. So you don't need to edit this.
 ### But pay attention to `$name`, it may be different. You can find the path in the configuration file.
 pidFile=/var/run/$name.pid
+
+script=$(basename "$0")
 
 getPid() {
     ### Delete spaces, tabs and newlines.
@@ -46,9 +48,13 @@ getPid() {
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
     ### apachectl is a script for running httpd, so we can't use its pid.
-    $bin -f "$config" > /dev/null 2>&1 &
+    if $bin -f "$config" > /dev/null 2>&1 & then
+        echo -n '.'
+        getPid
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
+    fi
 
-    getPid
     for (( i=0; i<=5; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             echo -n '.'
@@ -64,12 +70,17 @@ doStart() {
 ### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
     echo -en "\033[1;36m[I]\033[0m  Gracefully stopping $name"
-    kill -WINCH $pid
+    if kill -WINCH $pid; then
+        echo -n '.'
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
+        exit 1
+    fi
 
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
                 exit 1
             fi
             echo -n '.'
@@ -160,7 +171,6 @@ case "$1" in
     ;;
 
     *)
-    script=$(basename "$0")
     echo "Usage: [sudo] $script {start|stop|kill|reload|restart|status}." >&2
     exit 3
     ;;
diff --git a/mysqld b/mysqld
--- a/mysqld
+++ b/mysqld
@@ -20,7 +20,7 @@ if [ "$(id -u)" != "0" ]; then
     exit 3
 fi
 
-### Maybe you need to change these.
+### Maybe you need to modify these.
 name=mysqld
 ### mysqld_safe is the recommended way to start a mysqld server on Unix.
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
@@ -32,6 +32,8 @@ config=/home/www/etc/my.cnf
 ### But pay attention to `$name`, it may be different. You can find the path in the configuration file.
 pidFile=/var/run/$name.pid
 
+script=$(basename "$0")
+
 getPid() {
     ### Delete spaces, tabs and newlines.
     pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
@@ -42,11 +44,15 @@ getPid() {
     fi
 }
 
-### Successfully start the application if the progress exists after 5 seconds.
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
     ### mysqld_safe is a script for running mysqld, so we can't use its pid.
-    $bin --defaults-file="$config" > /dev/null 2>&1 &
+    if $bin --defaults-file="$config" > /dev/null 2>&1 & then
+        echo -n '.'
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
+        exit 1
+    fi
 
     ### Wait for mysqld start. Try waiting for a longer time if start mysqld failed.
     for (( i=0; i<=3; i++ )); do
@@ -55,6 +61,7 @@ doStart() {
     done
 
     getPid
+    ### Successfully start the application if the progress exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             echo -n '.'
@@ -67,15 +74,20 @@ doStart() {
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
-### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
     echo -en "\033[1;36m[I]\033[0m  Stopping $name"
-    kill $pid
+    if kill $pid; then
+        echo -n '.'
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error."
+        exit 1
+    fi
 
+    ### Successfully stop the application if the progress doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed."
                 exit 1
             fi
             echo -n '.'
@@ -132,8 +144,7 @@ case "$1" in
     ;;
 
     *)
-    script=$(basename "$0")
-    ### You can't reload the configuration file in here, but you can use `SET` statement to change server system variables dynamically.
+    ### You can't reload the configuration file in here, but you can use `SET` statement to modify server system variables dynamically.
     ### See https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html and https://dev.mysql.com/doc/refman/5.6/en/set-statement.html.
     ### You also can't forcefully kill mysqld, it's not safe. And mysqld_safe will rerun mysqld.
 #   echo "Usage: [sudo] $script {start|stop|kill|restart|reload|status}" >&2
diff --git a/nginx b/nginx
--- a/nginx
+++ b/nginx
@@ -20,7 +20,7 @@ if [ "$(id -u)" != "0" ]; then
     exit 3
 fi
 
-### Maybe you need to change these.
+### Maybe you need to modify these.
 name=nginx
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
 ### Try use `which $name` to find the full path, or just use `$name` if it is in `$PATH`.
@@ -29,6 +29,8 @@ bin=/usr/local/nginx/sbin/$name
 config=/home/www/etc/nginx/$name.conf
 ### By default, the pid file of programs are in `/var/run`. So you don't need to edit this. You can find the path in the configuration file.
 pidFile=/var/run/$name.pid
+
+script=$(basename "$0")
 
 getPid() {
     ### Delete spaces, tabs and newlines.
@@ -40,12 +42,17 @@ getPid() {
     fi
 }
 
-### Successfully start the application if the progress exists after 5 seconds.
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
-    $bin -c "$config"
+    if $bin -c "$config"; then
+        echo -n '.'
+        getPid
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
+        exit 1
+    fi
 
-    getPid
+    ### Successfully start the application if the progress exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             echo -n '.'
@@ -58,15 +65,20 @@ doStart() {
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
-### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
     echo -en "\033[1;36m[I]\033[0m  Gracefully stopping $name"
-    kill -QUIT $pid
+    if kill -QUIT $pid; then
+        echo -n '.'
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
+        exit 1
+    fi
 
+    ### Successfully stop the application if the progress doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
                 exit 1
             fi
             echo -n '.'
@@ -157,7 +169,6 @@ case "$1" in
     ;;
 
     *)
-    script=$(basename "$0")
     echo "Usage: [sudo] $script {start|stop|kill|reload|restart|status}." >&2
     exit 3
     ;;
diff --git a/php-fpm b/php-fpm
--- a/php-fpm
+++ b/php-fpm
@@ -20,7 +20,7 @@ if [ "$(id -u)" != "0" ]; then
     exit 3
 fi
 
-### Maybe you need to change these.
+### Maybe you need to modify these.
 name=php-fpm
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
 ### Try use `which $name` to find the full path, or just use `$name` if it is in `$PATH`.
@@ -30,6 +30,8 @@ config=/home/www/etc/php/$name.conf
 ini=/home/www/etc/php/php.ini
 ### By default, the pid file of programs are in `/var/run`. So you don't need to edit this. You can find the path in the configuration file.
 pidFile=/var/run/$name.pid
+
+script=$(basename "$0")
 
 getPid() {
     ### Delete spaces, tabs and newlines.
@@ -41,13 +43,18 @@ getPid() {
     fi
 }
 
-### Successfully start the application if the progress exists after 5 seconds.
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
     ### Block zend version notice.
-    $bin -c "$ini" -y "$config" > /dev/null 2>&1
+    if $bin -c "$ini" -y "$config" > /dev/null 2>&1; then
+        echo -n '.'
+        getPid
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
+        exit 1
+    fi
 
-    getPid
+    ### Successfully start the application if the progress exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             echo -n '.'
@@ -60,15 +67,20 @@ doStart() {
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
-### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
     echo -en "\033[1;36m[I]\033[0m  Gracefully stopping $name"
-    kill -QUIT $pid
+    if kill -QUIT $pid; then
+        echo -n '.'
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
+        exit 1
+    fi
 
+    ### Successfully stop the application if the progress doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
                 exit 1
             fi
             echo -n '.'
@@ -159,7 +171,6 @@ case "$1" in
     ;;
 
     *)
-    script=$(basename "$0")
     echo "Usage: [sudo] $script {start|stop|kill|reload|restart|status}." >&2
     exit 3
     ;;
diff --git a/rsyncd b/rsyncd
--- a/rsyncd
+++ b/rsyncd
@@ -20,13 +20,15 @@ if [ "$(id -u)" != "0" ]; then
     exit 3
 fi
 
-### Maybe you need to change these.
+### Maybe you need to modify these.
 name=rsyncd
 ### In the most cases, the configuration file of programs are in `/etc`. You can create your own configuration file and edit this to the new path.
 config=/home/www/etc/rsync/$name.conf
 ### By default, the pid file of programs are in `/var/run`. So you don't need to edit this.
 ### But pay attention to `$name`, it may be different. You can find the path in the configuration file.
 pidFile=/var/run/$name.pid
+
+script=$(basename "$0")
 
 getPid() {
     ### Delete spaces, tabs and newlines.
@@ -38,13 +40,18 @@ getPid() {
     fi
 }
 
-### Successfully start the application if the progress exists after 5 seconds.
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
     ### rsync is built-in in most of linux distribution.
-    rsync --daemon --config="$config"
+    if rsync --daemon --config="$config"; then
+        echo -n '.'
+        getPid
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
+        exit 1
+    fi
 
-    getPid
+    ### Successfully start the application if the progress exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             echo -n '.'
@@ -57,15 +64,21 @@ doStart() {
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
-### Successfully stop the application if the progress doesn't exists in 10 seconds.
+
 doStop() {
     echo -en "\033[1;36m[I]\033[0m  Stopping $name"
-    kill $pid
+    if kill $pid; then
+        echo -n '.'
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
+        exit 1
+    fi
 
+    ### Successfully stop the application if the progress doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
                 exit 1
             fi
             echo -n '.'
@@ -140,7 +153,6 @@ case "$1" in
     ;;
 
     *)
-    script=$(basename "$0")
     echo "Usage: [sudo] $script {start|stop|kill|restart|status}." >&2
     exit 3
     ;;
diff --git a/ssserver b/ssserver
--- a/ssserver
+++ b/ssserver
@@ -20,7 +20,7 @@ if [ "$(id -u)" != "0" ]; then
     exit 3
 fi
 
-### Maybe you need to change these.
+### Maybe you need to modify these.
 name=ssserver
 ### shadowsocks need python2 or node.js to run it.
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
@@ -28,10 +28,12 @@ name=ssserver
 bin=/usr/local/node/bin/$name
 ### In the most cases, the configuration file of programs are in `/etc`. You can create your own configuration file and edit this to the new path.
 config=/home/www/etc/shadowsocks.json
-### In the most cases, the log file of programs are in `/var/log`. You are free to change this.
+### In the most cases, the log file of programs are in `/var/log`. You are free to modify this.
 log=/home/www/log/shadowsocks.log
-### By default, the pid file of programs are in `/var/run`. So you don't need to change this.
+### By default, the pid file of programs are in `/var/run`. So you don't need to modify this.
 pidFile=/var/run/$name.pid
+
+script=$(basename "$0")
 
 getPid() {
     ### Delete spaces, tabs and newlines.
@@ -43,12 +45,18 @@ getPid() {
     fi
 }
 
-### Successfully start the application if the progress exists after 5 seconds.
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
-    nohup $bin -c "$config" >> "$log" 2>&1 & echo -n $! > $pidFile
+    if nohup $bin -c "$config" >> "$log" 2>&1 & then
+        echo -n '.'
+        pid=$!
+        echo -n $pid > $pidFile
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
+        exit 1
+    fi
 
-    pid=$!
+    ### Successfully start the application if the progress exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             echo -n '.'
@@ -62,15 +70,21 @@ doStart() {
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
-### Successfully stop the application if the progress doesn't exists in 10 seconds.
+
 doStop() {
     echo -en "\033[1;36m[I]\033[0m  Stopping $name"
-    kill $pid
+    if kill $pid; then
+        echo -n '.'
+    else
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
+        exit 1
+    fi
 
+    ### Successfully stop the application if the progress doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
                 exit 1
             fi
             echo -n '.'
@@ -146,8 +160,7 @@ case "$1" in
     ;;
 
     *)
-    script=$(basename "$0")
-    echo "Usage: $0 {start|stop|kill|restart|status}." >&2
+    echo "Usage: [sudo] $script {start|stop|kill|restart|status}." >&2
     exit 3
     ;;
 esac
