refactoring

diff --git a/aria2c b/aria2c
--- a/aria2c
+++ b/aria2c
@@ -13,7 +13,7 @@
 PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
 export PATH
 
-if [ "$(id -u)" != "0" ]; then
+if [ $(id -u) -ne 0 ]; then
     echo -e "\033[1;31m[E]\033[0m  You must have root permissions for run this script, please use sudo and try again." >&2
     exit 4
 fi
@@ -44,6 +44,10 @@ log=/var/log/aria2.log
 ### By default, the pid file of program is in `/var/run`. So you don't need to edit this variable.
 pidFile=/var/run/$name.pid
 
+### Modify these variables to your own path.
+dlDir=/media/Files/Downloads
+sessionFile=$dlDir/aria2.session
+
 ##########                                           ##########
 ###############################################################
 
@@ -52,6 +56,7 @@ script=$(basename "$0")
 getPid() {
     ### Delete spaces, tabs and newlines.
     pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
+
     ### `$pidFile` may be blank. If the process exists, `! kill -0 $pid 2>/dev/null` will return 1.
     if [ -z $pid ] || ! kill -0 $pid 2>/dev/null; then
         rm -f $pidFile
@@ -59,72 +64,68 @@ getPid() {
     fi
 }
 
-### Modify these variables to your own path.
-dlDir=/media/Files/Downloads
-sessionFile=$dlDir/aria2.session
 
-### Modify 'pi' to your own username.
-checkDlDir() {
+doStart() {
+    echo -en "\033[1;36m[I]\033[0m  Starting $name."
+
+    ### aria2 doesn't create these files automatically, so we need to create them manually.
+    ### Modify 'pi' to your own username.
     if [ ! -d "$dlDir" ]; then
         mkdir -p "$dlDir"
+        chown -R pi:pi "$dlDir"
     fi
+
     if [ ! -w "$sessionFile" ]; then
         touch "$sessionFile"
     fi
-    chown -R pi:pi "$dlDir"
+
     if [ ! -w "$log" ]; then
         touch "$log"
         chown pi:pi "$log"
     fi
-}
 
-doStart() {
-    echo -en "\033[1;36m[I]\033[0m  Starting $name"
-    ### aria2 doesn't create these files automatically, so we need to create them manually.
-    checkDlDir
     ### I don't want it to run as root. aria2 doesn't create a pid file.
-    if su pi -s /bin/bash -c "$bin --conf-path='$config'"; then
-        echo -n '.'
-        pid=$(pgrep -f $bin)
-        echo -n $pid > $pidFile
-    else
+    if ! su pi -s /bin/bash -c "$bin --conf-path='$config'"; then
         echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
         exit 1
     fi
 
+    pid=$(pgrep -f $bin)
+    echo -n $pid > $pidFile
+
     ### Successfully start the program if the process exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
-        if kill -0 $pid 2>/dev/null; then
-            echo -n '.'
-            sleep 1
-        else
+        if ! kill -0 $pid 2>/dev/null; then
             rm -f $pidFile
             echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
             exit 1
         fi
+
+        sleep 1
+        echo -n '.'
     done
+
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
 doStop() {
-    echo -en "\033[1;36m[I]\033[0m  Stopping $name"
-    if kill $pid; then
-        echo -n '.'
-    else
+    echo -en "\033[1;36m[I]\033[0m  Stopping $name."
+
+    if ! kill $pid; then
         echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
         exit 1
     fi
 
     ### Successfully stop the program if the process doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
-        if kill -0 $pid 2>/dev/null; then
-            echo -n '.'
-            sleep 1
-        else
+        if ! kill -0 $pid 2>/dev/null; then
             rm -f $pidFile
             echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
             return 0
         fi
+
+        sleep 1
+        echo -n '.'
     done
 
     echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
@@ -135,74 +136,78 @@ case "$1" in
     start)
     getPid
     if [ $pid ]; then
-        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid"
-    else
-        doStart
+        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid."
+        exit 0
     fi
+
+    doStart
     ;;
 
     stop)
     getPid
-    if [ $pid ]; then
-        doStop
-    else
+    if [ -z $pid ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
+        exit 0
     fi
+
+    doStop
     ;;
 
     kill)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Forcefully killing the process of $name..."
-
-        if kill -9 $pid; then
-            rm -f $pidFile
-            echo -e "\033[1;32m[N]\033[0m  Kill $name done."
-        else
-            echo -e "\033[1;31m[E]\033[0m  Kill $name error."
-            exit 1
-        fi
-    else
+    if [ -z $pid ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
+        exit 0
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Forcefully killing the process of $name..."
+
+    if ! kill -9 $pid; then
+        echo -e "\033[1;31m[E]\033[0m  Kill $name error."
+        exit 1
+    fi
+
+    rm -f $pidFile
+    echo -e "\033[1;32m[N]\033[0m  Kill $name done."
     ;;
 
     restart)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Restarting $name:"
-        doStop
+    if [ -z $pid ]; then
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         doStart
-    else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
-        doStart
+        exit 0
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Restarting $name:"
+    doStop
+    doStart
     ;;
 
     force-reload)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Forcefully reloading (restarting) $name:"
-        doStop
-        doStart
-    else
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
+    if [ -z $pid ]; then
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running."
         exit 7
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Forcefully reloading (restarting) $name:"
+    doStop
+    doStart
     ;;
 
     status)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
-    else
+    if [ -z $pid ]; then
         echo -e "\033[1;32m[N]\033[0m  $name isn't running."
         exit 3
     fi
+
+    echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid."
     ;;
 
     *)
-    echo "Usage: [sudo] $script {start|stop|kill|restart|force-reload|force-reload|status}." >&2
+    echo "Usage: [sudo] $script {start|stop|kill|restart|force-reload|status}." >&2
     exit 3
     ;;
 esac
diff --git a/httpd b/httpd
--- a/httpd
+++ b/httpd
@@ -13,7 +13,7 @@
 PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
 export PATH
 
-if [ "$(id -u)" != "0" ]; then
+if [ $(id -u) -ne 0 ]; then
     echo -e "\033[1;31m[E]\033[0m  You must have root permissions for run this script, please use sudo and try again." >&2
     exit 4
 fi
@@ -51,6 +51,7 @@ script=$(basename "$0")
 getPid() {
     ### Delete spaces, tabs and newlines.
     pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
+
     ### `$pidFile` may be blank. If the process exists, `! kill -0 $pid 2>/dev/null` will return 1.
     if [ -z $pid ] || ! kill -0 $pid 2>/dev/null; then
         rm -f $pidFile
@@ -60,45 +61,46 @@ getPid() {
 
 ### Successfully start the application if the process exists after 5 seconds.
 doStart() {
-    echo -en "\033[1;36m[I]\033[0m  Starting $name"
+    echo -en "\033[1;36m[I]\033[0m  Starting $name."
+
     ### apachectl is a script for running httpd, so we can't use its pid.
-    if $bin -f "$config" & then
-        echo -n '.'
-        getPid
-    else
+    if ! $bin -f "$config" & then
         echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
+        exit 1
     fi
 
+    getPid
+
     for (( i=0; i<=5; i++ )); do
-        if kill -0 $pid 2>/dev/null; then
-            echo -n '.'
-            sleep 1
-        else
+        if ! kill -0 $pid 2>/dev/null; then
             echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
             exit 1
         fi
+
+        sleep 1
+        echo -n '.'
     done
+
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
 ### Successfully stop the program if the process doesn't exists in 10 seconds.
 doStop() {
-    echo -en "\033[1;36m[I]\033[0m  Gracefully stopping $name"
-    if kill -WINCH $pid; then
-        echo -n '.'
-    else
+    echo -en "\033[1;36m[I]\033[0m  Gracefully stopping $name."
+
+    if ! kill -WINCH $pid; then
         echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
         exit 1
     fi
 
     for (( i=0; i<=10; i++ )); do
-        if kill -0 $pid 2>/dev/null; then
-            echo -n '.'
-            sleep 1
-        else
+        if ! kill -0 $pid 2>/dev/null; then
             echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
             return 0
         fi
+
+        sleep 1
+        echo -n '.'
     done
 
     echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
@@ -109,86 +111,90 @@ case "$1" in
     start)
     getPid
     if [ $pid ]; then
-        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid"
-    else
-        doStart
+        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid."
+        exit 0
     fi
+
+    doStart
     ;;
 
     stop)
     getPid
-    if [ $pid ]; then
-        doStop
-    else
+    if [ -z $pid ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
+        exit 0
     fi
+
+    doStop
     ;;
 
     kill)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Fast Shutdown $name..."
-
-        if kill -TERM $pid; then
-            echo -e "\033[1;32m[N]\033[0m  Shutdown $name done."
-        else
-            echo -e "\033[1;31m[E]\033[0m  Shutdown $name error."
-            exit 1
-        fi
-    else
+    if [ -z $pid ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
+        exit 0
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Fast Shutdown $name..."
+
+    if ! kill -TERM $pid; then
+        echo -e "\033[1;31m[E]\033[0m  Shutdown $name error."
+        exit 1
+    fi
+
+    echo -e "\033[1;32m[N]\033[0m  Shutdown $name done."
     ;;
 
     restart)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Restarting $name:"
-        doStop
+    if [ -z $pid ]; then
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         doStart
-    else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
-        doStart
+        exit 0
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Restarting $name:"
+    doStop
+    doStart
     ;;
 
     reload)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Reloading $name configuration file..."
-
-        if kill -USR1 $pid; then
-            echo -e "\033[1;32m[N]\033[0m  Reload $name done."
-        else
-            echo -e "\033[1;31m[E]\033[0m  Reload $name error."
-            exit 1
-        fi
-    else
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
+    if [ -z $pid ]; then
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running."
         exit 7
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Reloading $name configuration file..."
+
+    if ! kill -USR1 $pid; then
+        echo -e "\033[1;31m[E]\033[0m  Reload $name configuration file error."
+        exit 1
+    fi
+
+    echo -e "\033[1;32m[N]\033[0m  Reload $name configuration file done."
     ;;
 
     force-reload)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Forcefully reloading (restarting) $name:"
-        doStop
-        doStart
-    else
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
+    if [ -z $pid ]; then
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running."
         exit 7
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Forcefully reloading (restarting) $name:"
+    doStop
+    doStart
     ;;
 
     status)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
-    else
+    if [ -z $pid ]; then
         echo -e "\033[1;32m[N]\033[0m  $name isn't running."
         exit 3
     fi
+
+    echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid."
     ;;
 
     *)
diff --git a/nginx b/nginx
--- a/nginx
+++ b/nginx
@@ -13,7 +13,7 @@
 PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
 export PATH
 
-if [ "$(id -u)" != "0" ]; then
+if [ $(id -u) -ne 0 ]; then
     echo -e "\033[1;31m[E]\033[0m  You must have root permissions for run this script, please use sudo and try again." >&2
     exit 4
 fi
@@ -49,6 +49,7 @@ script=$(basename "$0")
 getPid() {
     ### Delete spaces, tabs and newlines.
     pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
+
     ### `$pidFile` may be blank. If the process exists, `! kill -0 $pid 2>/dev/null` will return 1.
     if [ -z $pid ] || ! kill -0 $pid 2>/dev/null; then
         rm -f $pidFile
@@ -57,46 +58,46 @@ getPid() {
 }
 
 doStart() {
-    echo -en "\033[1;36m[I]\033[0m  Starting $name"
-    if $bin -c "$config"; then
-        echo -n '.'
-        getPid
-    else
+    echo -en "\033[1;36m[I]\033[0m  Starting $name."
+
+    if ! $bin -c "$config"; then
         echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
         exit 1
     fi
 
+    getPid
+
     ### Successfully start the program if the process exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
-        if kill -0 $pid 2>/dev/null; then
-            echo -n '.'
-            sleep 1
-        else
+        if ! kill -0 $pid 2>/dev/null; then
             echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
             exit 1
         fi
+
+        sleep 1
+        echo -n '.'
     done
+
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
 doStop() {
-    echo -en "\033[1;36m[I]\033[0m  Gracefully stopping $name"
-    if kill -QUIT $pid; then
-        echo -n '.'
-    else
+    echo -en "\033[1;36m[I]\033[0m  Gracefully stopping $name."
+
+    if ! kill -QUIT $pid; then
         echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
         exit 1
     fi
 
     ### Successfully stop the program if the process doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
-        if kill -0 $pid 2>/dev/null; then
-            echo -n '.'
-            sleep 1
-        else
+        if ! kill -0 $pid 2>/dev/null; then
             echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
             return 0
         fi
+
+        sleep 1
+        echo -n '.'
     done
 
     echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
@@ -107,90 +108,111 @@ case "$1" in
     start)
     getPid
     if [ $pid ]; then
-        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid"
-    else
-        doStart
+        echo -e "\033[1;33m[W]\033[0m  $name is already running. pid = $pid."
+        exit 0
     fi
+
+    doStart
     ;;
 
     stop)
     getPid
-    if [ $pid ]; then
-        doStop
-    else
+    if [ -z $pid ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
+        exit 0
     fi
+
+    doStop
     ;;
 
     kill)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Fast Shutdown $name..."
-
-        if kill -TERM $pid; then
-            echo -e "\033[1;32m[N]\033[0m  Shutdown $name done."
-        else
-            echo -e "\033[1;31m[E]\033[0m  Shutdown $name error."
-            exit 1
-        fi
-    else
+    if [ -z $pid ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
+        exit 0
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Fast Shutdown $name..."
+
+    if ! kill -TERM $pid; then
+        echo -e "\033[1;31m[E]\033[0m  Shutdown $name error."
+        exit 1
+    fi
+
+    echo -e "\033[1;32m[N]\033[0m  Shutdown $name done."
     ;;
 
     restart)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Restarting $name:"
-        doStop
+    if [ -z $pid ]; then
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         doStart
-    else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
-        doStart
+        exit 0
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Restarting $name:"
+    doStop
+    doStart
     ;;
 
     reload)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Reloading $name configuration file..."
-
-        if kill -HUP $pid; then
-            echo -e "\033[1;32m[N]\033[0m  Reload $name done."
-        else
-            echo -e "\033[1;31m[E]\033[0m  Reload $name error."
-            exit 1
-        fi
-    else
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
+    if [ -z $pid ]; then
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running."
         exit 7
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Reloading $name configuration file..."
+
+    if ! kill -HUP $pid; then
+        echo -e "\033[1;31m[E]\033[0m  Reload $name configuration file error."
+        exit 1
+    fi
+
+    echo -e "\033[1;32m[N]\033[0m  Reload $name configuration file done."
     ;;
 
     force-reload)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;36m[I]\033[0m  Forcefully reloading (restarting) $name:"
-        doStop
-        doStart
-    else
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
+    if [ -z $pid ]; then
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running."
         exit 7
     fi
+
+    echo -e "\033[1;36m[I]\033[0m  Forcefully reloading (restarting) $name:"
+    doStop
+    doStart
     ;;
 
     status)
     getPid
-    if [ $pid ]; then
-        echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
-    else
+    if [ -z $pid ]; then
         echo -e "\033[1;32m[N]\033[0m  $name isn't running."
         exit 3
     fi
+
+    echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid."
+    ;;
+
+    reopen-log)
+    getPid
+    if [ -z $pid ]; then
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running."
+        exit 7
+    fi
+
+    echo -e "\033[1;36m[I]\033[0m  Relopen $name log files file..."
+
+    if ! kill -USR1 $pid; then
+        echo -e "\033[1;31m[E]\033[0m  Relopen $name log files error."
+        exit 1
+    fi
+
+    echo -e "\033[1;32m[N]\033[0m  Relopen $name log files done."
     ;;
 
     *)
-    echo "Usage: [sudo] $script {start|stop|kill|restart|reload|force-reload|status}." >&2
+    echo "Usage: [sudo] $script {start|stop|kill|restart|reload|force-reload|status|reopen-log}." >&2
     exit 3
     ;;
 esac
