update. added php-fpm.
Signed-off-by: Jat <dpjat1@gmail.com>

diff --git a/aria2c b/aria2c
--- a/aria2c
+++ b/aria2c
@@ -12,25 +12,23 @@
 # Description: aria2 is a lightweight multi-protocol & multi-source command-line download utility.
 ### END INIT INFO
 
-bin=/usr/bin/aria2c
-conf=/etc/aria2.conf
-pidFile=/var/run/aria2c.pid
-if [ -f "$pidFile" ]; then
-    pid=$(cat $pidFile)
-    checkProgress=$(kill -0 $pid 2>&1 > /dev/null && echo -n $?)
-    if [ "$checkProgress" != "0" ]; then
+name=aria2c
+bin=/usr/bin/$name
+config=/etc/aria2.conf
+pidFile=/var/run/$name.pid
+
+getPid() {
+    ### Delete spaces, tabs and newlines.
+    pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
+    if [ "$pid" ] && [ ! -d "/proc/$pid" ]; then
         rm -f $pidFile
         unset pid
     fi
-fi
-script=/etc/init.d/aria2c
+}
+
 log=/var/log/aria2.log
 dlDir=/media/Files/Downloads
 sessionFile=$dlDir/aria2.session
-
-aria2() {
-    $bin --conf-path="$conf" && pidof $bin > $pidFile
-}
 
 checkDlDir() {
     if [ ! -d "$dlDir" ]; then
@@ -44,70 +42,107 @@ checkDlDir() {
     fi
 }
 
+### Successfully start the application if the progress exists after 3 seconds.
 doStart() {
-    if [ "$pid" ]; then
-        echo "aria2 daemon already running. pid = $pid"
-    else
-        checkDlDir
-        aria2
-        echo 'Done.'
-    fi
+    echo -en "\033[1;36m[I]\033[0m  Starting $name"
+    ### aria2 doesn't create these file automatically, so we need create it manually.
+    checkDlDir
+    ### I can't use `$!` to get the pid, and aria2 doesn't create pid file too.
+    $bin --conf-path="$config" && pidof $bin > $pidFile
+
+    getPid
+    for (( i=0; i<=5; i++ )); do
+        if [ -d "/proc/$pid" ]; then
+            echo -n '.'
+            sleep 1
+        else
+            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
+            exit 1
+        fi
+    done
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
 }
 
+### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
-    if [ "$pid" ]; then
-        kill $pid
-        rm -f $pidFile
-        echo 'Done.'
-    else
-        echo 'aria2 daemon not running.'
-    fi
-}
+    echo -en "\033[1;36m[I]\033[0m  Stopping $name"
+    kill $pid
 
-doRestart() {
-    if [ "$pid" ]; then
-        echo 'Stopping aria2 daemon...'
-        kill $pid
-        rm -f $pidFile
-        echo 'Done'
-        sleep 1
-        echo 'Starting aria2 daemon...'
-        aria2
-        echo 'Done.'
-    else
-        echo -e 'aria2 daemon not running.\nStarting aria2 daemon...'
-        checkDlDir
-        aria2
-        echo 'Done.'
-    fi
-}
-
-checkStatus() {
-    if [ "$pid" ]; then
-        echo "aria2 daemon is running. pid = $pid"
-    else
-        echo 'aria2 daemon not running.'
-    fi
+    for (( i=0; i<=10; i++ )); do
+        if [ -d "/proc/$pid" ]; then
+            if [ "$i" = "10" ]; then
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                exit 1
+            fi
+            echo -n '.'
+            sleep 1
+        else
+            rm -f $pidFile
+            ### Just for restart.
+            unset pid
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            break
+        fi
+    done
 }
 
 case "$1" in
     start)
-    echo 'Starting aria2 daemon...'
-    doStart
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;33m[W]\033[0m  $name already running. pid = $pid"
+        exit 2
+    else
+        doStart
+    fi
     ;;
+
     stop)
-    echo 'Stopping aria2 daemon...'
-    doStop
+    getPid
+    if [ "$pid" ]; then
+        doStop
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
     ;;
+
+    kill)
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;36m[I]\033[0m  Forcefully killing the progress of $name..."
+        kill -9 $pid
+        rm -f $pidFile
+        echo -e "\033[1;32m[N]\033[0m  Kill $name Done."
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
+    ;;
+
     restart)
-    echo 'Restarting aria2 daemon: '
-    doRestart
+    getPid
+    echo -e "\033[1;36m[I]\033[0m  Restarting $name: "
+    if [ "$pid" ]; then
+        doStop
+        doStart
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        doStart
+    fi
     ;;
+
     status)
-    checkStatus
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
+    else
+        echo -e "\033[1;32m[N]\033[0m  $name not running."
+    fi
     ;;
+
     *)
-    echo "Usage: $script {start|stop|restart|status}" >&2
+    echo "Usage: $0 {start|stop|kill|restart|status}." >&2
     exit 3
     ;;
 esac
diff --git a/mysqld b/mysqld
--- a/mysqld
+++ b/mysqld
@@ -12,100 +12,110 @@
 # Description: MySQL is a very fast and reliable SQL database engine.
 ### END INIT INFO
 
+name=mysqld
 bin=/usr/local/mysql/bin/mysqld_safe
 config=/home/www/etc/my.cnf
-pidFile=/var/run/mysqld.pid
-if [ -f "$pidFile" ]; then
-    pid=$(cat $pidFile)
-    checkProgress=$(kill -0 $pid 2>&1 > /dev/null && echo -n $?)
-    if [ "$checkProgress" != "0" ]; then
+pidFile=/var/run/$name.pid
+
+getPid() {
+    ### Delete spaces, tabs and newlines.
+    pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
+    if [ "$pid" ] && [ ! -d "/proc/$pid" ]; then
         rm -f $pidFile
         unset pid
     fi
-fi
-script=/etc/init.d/mysqld
-
-mysql() {
-    $bin --defaults-file="$config" 2>&1 > /dev/null &
 }
 
+### Successfully start the application if the progress exists after 5 seconds.
 doStart() {
-    if [ "$pid" ]; then
-        echo "MySQL already running. pid = $pid"
-    else
-        mysql
-        echo 'Done.'
-    fi
+    echo -en "\033[1;36m[I]\033[0m  Starting $name"
+    ### mysqld_safe is a script for running mysqld, so we can't use its pid.
+    $bin --defaults-file="$config" > /dev/null 2>&1 &
+
+    getPid
+    for (( i=0; i<=5; i++ )); do
+        if [ -d "/proc/$pid" ]; then
+            echo -n '.'
+            sleep 1
+        else
+            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
+            exit 1
+        fi
+    done
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
 }
 
+### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
-    if [ "$pid" ]; then
-        kill $pid
-        echo 'Done.'
-    else
-        echo 'MySQL not running.'
-    fi
-}
+    echo -en "\033[1;36m[I]\033[0m  Stopping $name"
+    kill $pid
 
-doRestart() {
-    if [ "$pid" ]; then
-        echo 'Stopping MySQL...'
-        kill $pid
-        echo 'Done.'
-        sleep 1
-        echo 'Starting MySQL...'
-        mysql
-        echo 'Done.'
-    else
-        echo -e 'MySQL not running.\nStarting MySQL...'
-        mysql
-        echo 'Done.'
-    fi
-}
-
-### It doesn't work.
-#doReload() {
-#    if [ "$pid" ]; then
-#        kill -HUP $pid
-#        echo 'Done.'
-#    else
-#        echo -e 'MySQL not running.\nStarting MySQL...'
-#        mysql
-#        echo 'Done.'
-#    fi
-#}
-
-checkStatus() {
-    if [ "$pid" ]; then
-        echo "MySQL is running. pid = $pid"
-    else
-        echo 'MySQL not running.'
-    fi
+    for (( i=0; i<=10; i++ )); do
+        if [ -d "/proc/$pid" ]; then
+            if [ "$i" = "10" ]; then
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                exit 1
+            fi
+            echo -n '.'
+            sleep 1
+        else
+            rm -f $pidFile
+            ### Just for restart.
+            unset pid
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            break
+        fi
+    done
 }
 
 case "$1" in
     start)
-    echo 'Starting MySQL...'
-    doStart
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;33m[W]\033[0m  $name already running. pid = $pid"
+        exit 2
+    else
+        doStart
+    fi
     ;;
+
     stop)
-    echo 'Stopping MySQL...'
-    doStop
+    getPid
+    if [ "$pid" ]; then
+        doStop
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
     ;;
-#   reload)
-#   echo 'Reloading MySQL configuration...'
-#   doReload
-#   ;;
+
     restart)
-    echo 'Restarting MySQL: '
-    doRestart
+    getPid
+    echo -e "\033[1;36m[I]\033[0m  Restarting $name: "
+    if [ "$pid" ]; then
+        doStop
+        doStart
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        doStart
+    fi
     ;;
+
     status)
-    checkStatus
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
+    else
+        echo -e "\033[1;32m[N]\033[0m  $name not running."
+    fi
     ;;
+
     *)
-#   echo "Usage: $script {start|stop|restart|reload|status}" >&2
-    echo "Usage: $script {start|stop|restart|status}" >&2
+    ### You can't reload the configuration file in here, but you can use `SET` statement to change server system variables dynamically.
+    ### See https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html and https://dev.mysql.com/doc/refman/5.6/en/set-statement.html.
+    ### You also can't forcefully kill mysqld, it's not safe. And mysqld_safe will rerun mysqld.
+#   echo "Usage: $0 {start|stop|kill|restart|reload|status}" >&2
+    echo "Usage: $0 {start|stop|restart|status}." >&2
     exit 3
     ;;
 esac
diff --git a/nginx b/nginx
--- a/nginx
+++ b/nginx
@@ -10,96 +10,129 @@
 # Description:       starts and stop the nginx web server
 ### END INIT INFO
 
-bin=/usr/local/nginx/sbin/nginx
-config=/home/www/etc/nginx/nginx.conf
-pidFile=/var/run/nginx.pid
-if [ -f "$pidFile" ]; then
-    pid=$(cat $pidFile)
-    checkProgress=$(kill -0 $pid 2>&1 > /dev/null && echo -n $?)
-    if [ "$checkProgress" != "0" ]; then
+name=nginx
+bin=/usr/local/nginx/sbin/$name
+config=/home/www/etc/nginx/$name.conf
+pidFile=/var/run/$name.pid
+
+getPid() {
+    ### Delete spaces, tabs and newlines.
+    pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
+    if [ "$pid" ] && [ ! -d "/proc/$pid" ]; then
         rm -f $pidFile
         unset pid
     fi
-fi
-script=/etc/init.d/nginx
-
-nginx() {
-    $bin -c "$config"
 }
 
+### Successfully start the application if the progress exists after 3 seconds.
 doStart() {
-    if [ "$pid" ]; then
-        echo "nginx already running. pid = $pid"
-    else
-        nginx
-        echo 'Done.'
-    fi
+    echo -en "\033[1;36m[I]\033[0m  Starting $name"
+    $bin -c "$config"
+
+    getPid
+    for (( i=0; i<=5; i++ )); do
+        if [ -d "/proc/$pid" ]; then
+            echo -n '.'
+            sleep 1
+        else
+            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
+            exit 1
+        fi
+    done
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
 }
 
+### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
-    if [ "$pid" ]; then
-        kill $pid
-        echo 'Done.'
-    else
-        echo 'nginx not running.'
-    fi
-}
+    echo -en "\033[1;36m[I]\033[0m  Gracefully stopping $name"
+    kill -QUIT $pid
 
-doRestart() {
-    if [ "$pid" ]; then
-        echo 'Stopping nginx...'
-        kill $pid
-        echo -e 'Done.\nStarting nginx...'
-        nginx
-        echo 'Done.'
-    else
-        echo -e 'nginx not running.\nStarting nginx...'
-        nginx
-        echo 'Done.'
-    fi
-}
-
-doReload() {
-    if [ "$pid" ]; then
-        kill -HUP $pid
-        echo 'Done.'
-    else
-        echo -e 'nginx not running.\nStarting nginx...'
-        nginx
-        echo 'Done.'
-    fi
-}
-
-checkStatus() {
-    if [ "$pid" ]; then
-        echo "nginx is running. pid = $pid"
-    else
-        echo 'nginx not running.'
-    fi
+    for (( i=0; i<=10; i++ )); do
+        if [ -d "/proc/$pid" ]; then
+            if [ "$i" = "10" ]; then
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                exit 1
+            fi
+            echo -n '.'
+            sleep 1
+        else
+            rm -f $pidFile
+            ### Just for restart.
+            unset pid
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            break
+        fi
+    done
 }
 
 case "$1" in
     start)
-    echo 'Starting nginx...'
-    doStart
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;33m[W]\033[0m  $name already running. pid = $pid"
+        exit 2
+    else
+        doStart
+    fi
     ;;
+
     stop)
-    echo 'Stopping nginx...'
-    doStop
+    getPid
+    if [ "$pid" ]; then
+        doStop
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
     ;;
+
+    kill)
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;36m[I]\033[0m  Fast Shutdown $name..."
+        kill -TERM $pid
+        echo -e "\033[1;32m[N]\033[0m  Shutdown $name Done."
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
+    ;;
+
     reload)
-    echo 'Reloading nginx configuration...'
-    doReload
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;36m[I]\033[0m  Reloading $name configuration file..."
+        kill -HUP $pid
+        echo 'Done.'
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        doStart
+    fi
     ;;
+
     restart)
-    echo 'Restarting nginx: '
-    doRestart
+    getPid
+    echo -e "\033[1;36m[I]\033[0m  Restarting $name: "
+    if [ "$pid" ]; then
+        doStop
+        doStart
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        doStart
+    fi
     ;;
+
     status)
-    checkStatus
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
+    else
+        echo -e "\033[1;32m[N]\033[0m  $name not running."
+    fi
     ;;
+
     *)
-    echo "Usage: $script {start|stop|restart|reload|status}" >&2
+    echo "Usage: $0 {start|stop|kill|reload|restart|status}." >&2
     exit 3
     ;;
 esac
diff --git a/ssserver b/ssserver
--- a/ssserver
+++ b/ssserver
@@ -12,84 +12,119 @@
 # Description: sinosky shadowsocks server daemon
 ### END INIT INFO
 
-bin=/usr/bin/ssserver
+name=ssserver
+bin=/usr/bin/$name
 config=/home/www/etc/shadowsocks.json
 log=/home/www/log/shadowsocks.log
-pidFile=/var/run/ssserver.pid
-if [ -f "$pidFile" ]; then
-    pid=$(cat $pidFile)
-    checkProgress=$(kill -0 $pid 2>&1 > /dev/null && echo -n $?)
-    if [ "$checkProgress" != "0" ]; then
+pidFile=/var/run/$name.pid
+
+getPid() {
+    ### Delete spaces, tabs and newlines.
+    pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
+    if [ "$pid" ] && [ ! -d "/proc/$pid" ]; then
         rm -f $pidFile
         unset pid
     fi
-fi
-script=/etc/init.d/ssserver
-
-shadowsocks() {
-    nohup $bin -c "$config" >> "$log" 2>&1 & echo -n $! > $pidFile
 }
 
+### Successfully start the application if the progress exists after 5 seconds.
 doStart() {
-    if [ "$pid" ]; then
-        echo "shadowsocks already running. pid = $pid"
-    else
-        shadowsocks
-        echo 'Done.'
-    fi
+    echo -en "\033[1;36m[I]\033[0m  Starting $name"
+    nohup $bin -c "$config" >> "$log" 2>&1 & echo -n $! > $pidFile
+
+    pid=$!
+    for (( i=0; i<=5; i++ )); do
+        if [ -d "/proc/$pid" ]; then
+            echo -n '.'
+            sleep 1
+        else
+            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
+            exit 1
+        fi
+    done
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
 }
 
+### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
-    if [ "$pid" ]; then
-        kill $pid
-        rm -f $pidFile
-        echo 'Done.'
-    else
-        echo 'shadowsocks not running.'
-    fi
-}
+    echo -en "\033[1;36m[I]\033[0m  Stopping $name"
+    kill $pid
 
-doRestart() {
-    if [ "$pid" ]; then
-        echo 'Stopping shadowsocks...'
-        kill $pid
-        rm -f $pidFile
-        echo -e 'Done.\nStarting shadowsocks...'
-        shadowsocks
-        echo 'Done.'
-    else
-        echo -e 'shadowsocks not running.\nStarting shadowsocks...'
-        shadowsocks
-        echo 'Done.'
-    fi
-}
-
-checkStatus() {
-    if [ "$pid" ]; then
-        echo "shadowsocks is running. pid = $pid"
-    else
-        echo 'shadowsocks not running.'
-    fi
+    for (( i=0; i<=10; i++ )); do
+        if [ -d "/proc/$pid" ]; then
+            if [ "$i" = "10" ]; then
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                exit 1
+            fi
+            echo -n '.'
+            sleep 1
+        else
+            rm -f $pidFile
+            ### Just for restart.
+            unset pid
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            break
+        fi
+    done
 }
 
 case "$1" in
     start)
-    echo 'Starting shadowsocks...'
-    doStart
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;33m[W]\033[0m  $name already running. pid = $pid"
+        exit 2
+    else
+        doStart
+    fi
     ;;
+
     stop)
-    echo 'Stopping shadowsocks...'
-    doStop
+    getPid
+    if [ "$pid" ]; then
+        doStop
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
     ;;
+
+    kill)
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;36m[I]\033[0m  Forcefully killing the progress of $name..."
+        kill -9 $pid
+        rm -f $pidFile
+        echo -e "\033[1;32m[N]\033[0m  Kill $name Done."
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
+    ;;
+
     restart)
-    echo 'Restarting shadowsocks: '
-    doRestart
+    getPid
+    echo -e "\033[1;36m[I]\033[0m  Restarting $name: "
+    if [ "$pid" ]; then
+        doStop
+        doStart
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        doStart
+    fi
     ;;
+
     status)
-    checkStatus
+    getPid
+    if [ "$pid" ]; then
+        echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
+    else
+        echo -e "\033[1;32m[N]\033[0m  $name not running."
+    fi
     ;;
+
     *)
-    echo "Usage: $script {start|stop|restart|status}" >&2
+    echo "Usage: $0 {start|stop|kill|restart|status}." >&2
     exit 3
     ;;
 esac
