fix a typo and update cmsd.

diff --git a/cmsd b/cmsd
--- a/cmsd
+++ b/cmsd
@@ -2,8 +2,8 @@
 
 ### BEGIN INIT INFO
 # Provides:          cmsd
-# Required-Start:    $all
-# Required-Stop:     $all
+# Required-Start:    $local_fs $network $named $remote_fs $syslog
+# Required-Stop:     $local_fs $network $named $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: aliyun jiankong agent
@@ -20,21 +20,22 @@ fi
 
 ### Maybe you need to modify these variables.
 name=cmsd
-### cmsd is a script for running agent.
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
 ### Try use `which $name` to find the full path, or just use `$name` if it is in `$PATH`.
-cmsd=/usr/bin/$name
 bin=/usr/local/cms/bin/agent_cms
+### In the most cases, the configuration file of programs are in `/etc`. You can create your own configuration file and edit this variable to the new path.
+config=/usr/local/cms/config/token.cfg
+token=$(grep 'AGENT_TOKEN' $config | tr -d ' \t' | awk -F= '{print $2}' 2>/dev/null)
 ### By default, the pid file of programs are in `/var/run`. So you don't need to edit this variable.
 pidFile=/var/run/$name.pid
 
 script=$(basename "$0")
 
 getPid() {
-    ### Delete tabs and newlines.
+    ### agent_cms has two processes.
     pid1=$(awk '{print $1}' $pidFile 2>/dev/null)
     pid2=$(awk '{print $2}' $pidFile 2>/dev/null)
-    ### `$pidFile` may be blank. If the progress exists, `! kill -0 $pid 2>/dev/null` will return 1.
+    ### `$pidFile` may be blank. If the process exists, `! kill -0 $pid 2>/dev/null` will return 1.
     if [[ ! "$pid1" && ! "$pid2" ]] || ! kill -0 $pid1 2>/dev/null && ! kill -0 $pid2 2>/dev/null; then
         rm -f $pidFile
         unset pid1 pid2
@@ -43,51 +44,44 @@ getPid() {
 
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
-    ### cmsd is a script for running agent_cms, so we can't use its pid.
-    if $cmsd start; then
+    if $bin -d -t "$token" > /dev/null; then
         echo -n '.'
+        sleep 1
     else
         echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
         exit 1
     fi
 
-    ### Wait for agent start. Try waiting for a longer time if start agent failed.
-    for (( i=0; i<=5; i++ )); do
+    until [[ "$pid1" && "$pid2" ]]; do
+        pids=$(pgrep -f $bin)
+        if [ ! "$pids" ]; then
+            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
+            exit 1
+        fi
+        pid1=$(echo $pids | awk '{print $1}')
+        pid2=$(echo $pids | awk '{print $2}')
+
         echo -n '.'
         sleep 1
     done
 
-    pids=$(pgrep -f $bin)
     echo -n $pids > $pidFile
-    pid1=$(echo $pids | awk '{print $1}')
-    pid2=$(echo $pids | awk '{print $2}')
-
-    ### Successfully start the program if the progress exists after 5 seconds.
-    for (( i=0; i<=5; i++ )); do
-        if kill -0 $pid1 2>/dev/null && kill -0 $pid2 2>/dev/null; then
-            echo -n '.'
-            sleep 1
-        else
-            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
-            exit 1
-        fi
-    done
     echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
 
 doStop() {
     echo -en "\033[1;36m[I]\033[0m  Stopping $name"
-    if $cmsd stop; then
+    if kill -9 $pid1 2>/dev/null; then
         echo -n '.'
     else
-        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error."
         exit 1
     fi
 
-    ### Successfully stop the program if the progress doesn't exists in 10 seconds.
+    ### Successfully stop the program if the process doesn't exists in 10 seconds.
     for (( i=0; i<=10; i++ )); do
-        if kill -0 $pid1 2>/dev/null && kill -0 $pid2 2>/dev/null; then
+        if kill -0 $pid1 2>/dev/null || kill -0 $pid2 2>/dev/null; then
             if [ "$i" = "10" ]; then
                 echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed."
                 exit 1
@@ -95,6 +89,7 @@ doStop() {
             echo -n '.'
             sleep 1
         else
+            rm -f $pidFile
             ### Just for restart.
             unset pid1 pid2
             echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
