updated

diff --git a/goagent b/goagent
--- a/goagent
+++ b/goagent
@@ -60,7 +60,7 @@ doStart() {
             exit 1
         fi
     done
-    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
 ### Successfully stop the application if the progress doesn't exists in 10 seconds.
@@ -80,7 +80,7 @@ doStop() {
             rm -f $pidFile
             ### Just for restart.
             unset pid
-            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
             break
         fi
     done
@@ -102,7 +102,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -111,11 +111,16 @@ case "$1" in
     getPid
     if [ "$pid" ]; then
         echo -e "\033[1;36m[I]\033[0m  Forcefully killing the progress of $name..."
-        kill -9 $pid
-        rm -f $pidFile
-        echo -e "\033[1;32m[N]\033[0m  Kill $name Done."
+
+        if kill -9 $pid; then
+            rm -f $pidFile
+            echo -e "\033[1;32m[N]\033[0m  Kill $name done."
+        else
+            echo -e "\033[1;31m[E]\033[0m  Kill $name error."
+            exit 1
+        fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -127,7 +132,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -137,7 +142,7 @@ case "$1" in
     if [ "$pid" ]; then
         echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
     else
-        echo -e "\033[1;32m[N]\033[0m  $name not running."
+        echo -e "\033[1;32m[N]\033[0m  $name isn't running."
     fi
     ;;
 
diff --git a/httpd b/httpd
--- a/httpd
+++ b/httpd
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 ### BEGIN INIT INFO
-# Provides:          apache2
+# Provides:          httpd
 # Required-Start:    $local_fs $network $named $remote_fs $syslog
 # Required-Stop:     $local_fs $network $named $remote_fs $syslog
 # Should-Start:      $network $named
@@ -25,9 +25,9 @@ name=httpd
 ### The recommended method of invoking the httpd executable is to use the apachectl control script.
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
 ### Try use `which $name` to find the full path, or just use `apachectl` if it in `$PATH`.
-bin=/usr/local/apache2/bin/apachectl
+bin=/usr/local/apache/bin/apachectl
 ### In the most cases, the configuration file of programs are in `/etc`. You can create your own configuration file and edit this to the new path.
-config=/home/www/etc/apache2/$name.conf
+config=/home/www/etc/apache/$name.conf
 ### By default, the pid file of programs are in `/var/run`. So you don't need to edit this.
 ### But pay attention to `$name`, it may be different. You can find the path in the configuration file.
 pidFile=/var/run/$name.pid
@@ -58,7 +58,7 @@ doStart() {
             exit 1
         fi
     done
-    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
 ### Successfully stop the application if the progress doesn't exists in 10 seconds.
@@ -77,7 +77,7 @@ doStop() {
         else
             ### Just for restart.
             unset pid
-            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
             break
         fi
     done
@@ -99,7 +99,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -108,10 +108,15 @@ case "$1" in
     getPid
     if [ "$pid" ]; then
         echo -e "\033[1;36m[I]\033[0m  Fast Shutdown $name..."
-        kill -TERM $pid
-        echo -e "\033[1;32m[N]\033[0m  Shutdown $name Done."
+
+        if kill -TERM $pid; then
+            echo -e "\033[1;32m[N]\033[0m  Shutdown $name done."
+        else
+            echo -e "\033[1;31m[E]\033[0m  Shutdown $name error."
+            exit 1
+        fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -120,10 +125,15 @@ case "$1" in
     getPid
     if [ "$pid" ]; then
         echo -e "\033[1;36m[I]\033[0m  Reloading $name configuration file..."
-        kill -USR1 $pid
-        echo -e "\033[1;32m[N]\033[0m  Reload $name Done."
+
+        if kill -USR1 $pid; then
+            echo -e "\033[1;32m[N]\033[0m  Reload $name done."
+        else
+            echo -e "\033[1;31m[E]\033[0m  Reload $name error."
+            exit 1
+        fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -135,7 +145,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -145,7 +155,7 @@ case "$1" in
     if [ "$pid" ]; then
         echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
     else
-        echo -e "\033[1;32m[N]\033[0m  $name not running."
+        echo -e "\033[1;32m[N]\033[0m  $name isn't running."
     fi
     ;;
 
diff --git a/lixian b/lixian
--- a/lixian
+++ b/lixian
@@ -25,7 +25,7 @@ name=lixian
 ### lixian need python2 to run it.
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
 ### Try use `which $name` to find the full path, or just use `$name` if the binary file in `$PATH`.
-python2=/usr/local/bin/python2
+python2=/usr/local/python2/bin/python2.7
 ### Edit this to your own path.
 app=/home/www/root/$name/main.py
 ### In the most cases, the configuration file of programs are in `/etc`. You can create your own configuration file and edit this to the new path.
@@ -61,7 +61,7 @@ doStart() {
             exit 1
         fi
     done
-    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
 ### Successfully stop the application if the progress doesn't exists in 10 seconds.
@@ -81,7 +81,7 @@ doStop() {
             rm -f $pidFile
             ### Just for restart.
             unset pid
-            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
             break
         fi
     done
@@ -103,7 +103,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -112,11 +112,16 @@ case "$1" in
     getPid
     if [ "$pid" ]; then
         echo -e "\033[1;36m[I]\033[0m  Forcefully killing the progress of $name..."
-        kill -9 $pid
-        rm -f $pidFile
-        echo -e "\033[1;32m[N]\033[0m  Kill $name Done."
+
+        if kill -9 $pid; then
+            rm -f $pidFile
+            echo -e "\033[1;32m[N]\033[0m  Kill $name done."
+        else
+            echo -e "\033[1;31m[E]\033[0m  Kill $name error."
+            exit 1
+        fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -128,7 +133,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -138,7 +143,7 @@ case "$1" in
     if [ "$pid" ]; then
         echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
     else
-        echo -e "\033[1;32m[N]\033[0m  $name not running."
+        echo -e "\033[1;32m[N]\033[0m  $name isn't running."
     fi
     ;;
 
diff --git a/nginx b/nginx
--- a/nginx
+++ b/nginx
@@ -55,7 +55,7 @@ doStart() {
             exit 1
         fi
     done
-    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
 ### Successfully stop the application if the progress doesn't exists in 10 seconds.
@@ -74,7 +74,7 @@ doStop() {
         else
             ### Just for restart.
             unset pid
-            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
             break
         fi
     done
@@ -96,7 +96,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -105,10 +105,15 @@ case "$1" in
     getPid
     if [ "$pid" ]; then
         echo -e "\033[1;36m[I]\033[0m  Fast Shutdown $name..."
-        kill -TERM $pid
-        echo -e "\033[1;32m[N]\033[0m  Shutdown $name Done."
+
+        if kill -TERM $pid; then
+            echo -e "\033[1;32m[N]\033[0m  Shutdown $name done."
+        else
+            echo -e "\033[1;31m[E]\033[0m  Shutdown $name error."
+            exit 1
+        fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -117,10 +122,15 @@ case "$1" in
     getPid
     if [ "$pid" ]; then
         echo -e "\033[1;36m[I]\033[0m  Reloading $name configuration file..."
-        kill -HUP $pid
-        echo -e "\033[1;32m[N]\033[0m  Reload $name Done."
+
+        if kill -HUP $pid; then
+            echo -e "\033[1;32m[N]\033[0m  Reload $name done."
+        else
+            echo -e "\033[1;31m[E]\033[0m  Reload $name error."
+            exit 1
+        fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -132,7 +142,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -142,7 +152,7 @@ case "$1" in
     if [ "$pid" ]; then
         echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
     else
-        echo -e "\033[1;32m[N]\033[0m  $name not running."
+        echo -e "\033[1;32m[N]\033[0m  $name isn't running."
     fi
     ;;
 
diff --git a/php-fpm b/php-fpm
--- a/php-fpm
+++ b/php-fpm
@@ -57,7 +57,7 @@ doStart() {
             exit 1
         fi
     done
-    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
 ### Successfully stop the application if the progress doesn't exists in 10 seconds.
@@ -76,7 +76,7 @@ doStop() {
         else
             ### Just for restart.
             unset pid
-            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
             break
         fi
     done
@@ -98,7 +98,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -107,10 +107,15 @@ case "$1" in
     getPid
     if [ "$pid" ]; then
         echo -e "\033[1;36m[I]\033[0m  Fast shutdown $name..."
-        kill -TERM $pid
-        echo -e "\033[1;32m[N]\033[0m  Shutdown $name Done."
+
+        if kill -TERM $pid; then
+            echo -e "\033[1;32m[N]\033[0m  Shutdown $name done."
+        else
+            echo -e "\033[1;31m[E]\033[0m  Shutdown $name error."
+            exit 1
+        fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -119,10 +124,15 @@ case "$1" in
     getPid
     if [ "$pid" ]; then
         echo -e "\033[1;36m[I]\033[0m  Reloading $name configuration file..."
-        kill -USR2 $pid
-        echo -e "\033[1;32m[N]\033[0m  Reload $name Done."
+
+        if kill -USR2 $pid; then
+            echo -e "\033[1;32m[N]\033[0m  Reload $name done."
+        else
+            echo -e "\033[1;31m[E]\033[0m  Reload $name error."
+            exit 1
+        fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -134,7 +144,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -144,7 +154,7 @@ case "$1" in
     if [ "$pid" ]; then
         echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
     else
-        echo -e "\033[1;32m[N]\033[0m  $name not running."
+        echo -e "\033[1;32m[N]\033[0m  $name isn't running."
     fi
     ;;
 
diff --git a/sslocal b/sslocal
--- a/sslocal
+++ b/sslocal
@@ -59,7 +59,7 @@ doStart() {
             exit 1
         fi
     done
-    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
 }
 
 ### Successfully stop the application if the progress doesn't exists in 10 seconds.
@@ -79,7 +79,7 @@ doStop() {
             rm -f $pidFile
             ### Just for restart.
             unset pid
-            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
             break
         fi
     done
@@ -101,7 +101,7 @@ case "$1" in
     if [ "$pid" ]; then
         doStop
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -110,11 +110,16 @@ case "$1" in
     getPid
     if [ "$pid" ]; then
         echo -e "\033[1;36m[I]\033[0m  Forcefully killing the progress of $name..."
-        kill -9 $pid
-        rm -f $pidFile
-        echo -e "\033[1;32m[N]\033[0m  Kill $name Done."
+
+        if kill -9 $pid; then
+            rm -f $pidFile
+            echo -e "\033[1;32m[N]\033[0m  Kill $name done."
+        else
+            echo -e "\033[1;31m[E]\033[0m  Kill $name error."
+            exit 1
+        fi
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 2
     fi
     ;;
@@ -126,7 +131,7 @@ case "$1" in
         doStop
         doStart
     else
-        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
         doStart
     fi
     ;;
@@ -136,7 +141,7 @@ case "$1" in
     if [ "$pid" ]; then
         echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
     else
-        echo -e "\033[1;32m[N]\033[0m  $name not running."
+        echo -e "\033[1;32m[N]\033[0m  $name isn't running."
     fi
     ;;
 
