make a simple thing complicated.
Signed-off-by: Jat <dpjat1@gmail.com>

diff --git a/lixian b/lixian
--- a/lixian
+++ b/lixian
@@ -9,88 +9,120 @@
 # Default-Start:  2 3 4 5
 # Default-Stop: 0 1 6
 # Short-Description: lixian daemon
-# Description: sinosky lixian server daemon
+# Description: sinosky lixian server daemon.
 ### END INIT INFO
 
+name=lixian
 python2=/usr/local/bin/python2
-lixianApp=/home/www/root/lixian/main.py
-config=/home/www/etc/lixian.conf
-log=/home/www/log/lixian.app.log
-pidFile=/var/run/lixian.pid
+app=/home/www/root/$name/main.py
+config=/home/www/etc/$name.conf
+log=/home/www/log/$name.app.log
+pidFile=/var/run/$name.pid
+
+doCheckProgress() {
+    kill -0 $1 > /dev/null 2>&1 && echo -n $?
+}
+
 if [ -f "$pidFile" ]; then
     pid=$(cat $pidFile)
-    checkProgress=$(kill -0 $pid 2>&1 > /dev/null && echo -n $?)
+    checkProgress=$(doCheckProgress $pid)
     if [ "$checkProgress" != "0" ]; then
         rm -f $pidFile
         unset pid
     fi
 fi
-script=/etc/init.d/lixian
 
-lixian() {
-    nohup $python2 $lixianApp --f="$config" >> "$log" 2>&1 & echo -n $! > $pidFile
-}
-
+### Successfully start the application if the progress exists after 3 seconds.
 doStart() {
-    if [ "$pid" ]; then
-        echo "lixian already running. pid = $pid"
-    else
-        lixian
-        echo 'Done.'
-    fi
+    echo -en "\033[1;36m[I]\033[0m  Starting $name"
+    nohup $python2 $app --f="$config" >> "$log" 2>&1 & echo -n $! > $pidFile
+    pidStart=$!
+    for (( i=0; i<=3; i++ )); do
+        checkProgress=$(doCheckProgress $pidStart)
+        if [ "$checkProgress" = "0" ]; then
+            echo -n '.'
+            sleep 1
+        else
+            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
+            exit 1
+        fi
+    done
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
 }
 
+### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
-    if [ "$pid" ]; then
-        kill $pid
-        rm -f $pidFile
-        echo 'Done.'
-    else
-        echo 'lixian not running.'
-    fi
-}
-
-doRestart() {
-    if [ "$pid" ]; then
-        echo 'Stopping lixian...'
-        kill $pid
-        rm -f $pidFile
-        echo -e 'Done.\nStarting lixian...'
-        lixian
-        echo 'Done.'
-    else
-        echo -e 'lixian not running.\nStarting lixian...'
-        lixian
-        echo 'Done.'
-    fi
-}
-
-checkStatus() {
-    if [ "$pid" ]; then
-        echo "lixian is running. pid = $pid"
-    else
-        echo 'lixian not running.'
-    fi
+    echo -en "\033[1;36m[I]\033[0m  Stopping $name"
+    kill $pid
+    for (( i=0; i<=10; i++ )); do
+        checkProgress=$(doCheckProgress $pid)
+        if [ "$checkProgress" = "0" ]; then
+            if [ "$i" = "10" ]; then
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                exit 1
+            fi
+            echo -n '.'
+            sleep 1
+        else
+            rm -f $pidFile
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            break
+        fi
+    done
 }
 
 case "$1" in
     start)
-    echo 'Starting lixian...'
-    doStart
+    if [ "$pid" ]; then
+        echo -e "\033[1;33m[W]\033[0m  $name already running. pid = $pid"
+        exit 2
+    else
+        doStart
+    fi
     ;;
+
     stop)
-    echo 'Stopping lixian...'
-    doStop
+    if [ "$pid" ]; then
+        doStop
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
     ;;
+
+    kill)
+    if [ "$pid" ]; then
+        echo -e "\033[1;36m[I]\033[0m  Force killing the progress of $name..."
+        kill -9 $pid
+        rm -f $pidFile
+        echo -e "\033[1;32m[N]\033[0m  Kill $name Done."
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
+    ;;
+
     restart)
-    echo 'Restarting lixian: '
-    doRestart
+    echo -e "\033[1;36m[I]\033[0m  Restarting $name: "
+    if [ "$pid" ]; then
+        doStop
+        doStart
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        doStart
+    fi
     ;;
+
     status)
-    checkStatus
+    if [ "$pid" ]; then
+        echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
+    else
+        echo -e "\033[1;32m[N]\033[0m  $name not running."
+    fi
     ;;
+
     *)
-    echo "Usage: $script {start|stop|restart|status}" >&2
+    echo "Usage: $0 {start|stop|kill|restart|status}." >&2
     exit 3
     ;;
 esac
