add awstats-cgi

diff --git a/munin-server b/munin-server
--- a/munin-server
+++ b/munin-server
@@ -25,8 +25,7 @@ name=munin
 
 ### In the most cases, the binary file of program is in `/usr/bin` or `/usr/local/bin`.
 ### Try using `which munin-node` `which spawn-fcgi` and `which fcgiwrap` to find the full path, or just use `munin-node` `spawn-fcgi` and `fcgiwrap` if it is in `$PATH`.
-prefix=/usr/local/munin
-node=$prefix/sbin/munin-node
+node=/usr/local/munin/sbin/munin-node
 spawnFcgi=/usr/bin/spawn-fcgi
 fcgiwrap=/usr/sbin/fcgiwrap
 if [ ! -x "$node" ] || [ ! -x "$spawnFcgi" ] || [ ! -x "$fcgiwrap" ]; then
@@ -114,7 +113,8 @@ doStart() {
         fi
 
         if [ ${#cgiPids[*]} -eq 0 ]; then
-            echo -e "\n\033[1;33m[W]\033[0m  Start munin-cgi failed."
+            echo -e "n\033[1;31m[E]\033[0m  Start munin-cgi failed."
+            exit 1
         fi
 
         for cgiPid in ${cgiPids[*]}; do
@@ -234,7 +234,7 @@ case "$1" in
 
     restart)
     getPid
-    if [ -z $nodePid ]; then
+    if [ -z $nodePid ] && [ ${#cgiPids[*]} -eq 0 ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         doStart
         exit 0
@@ -247,7 +247,7 @@ case "$1" in
 
     force-reload)
     getPid
-    if [ -z $nodePid ]; then
+    if [ -z $nodePid ] && [ ${#cgiPids[*]} -eq 0 ]; then
         echo -e "\033[1;31m[E]\033[0m  $name isn't running."
         exit 7
     fi
