fuck shell. i hate it.

diff --git a/munin-server b/munin-server
--- a/munin-server
+++ b/munin-server
@@ -25,12 +25,13 @@ name=munin
 
 ### In the most cases, the binary file of program is in `/usr/bin` or `/usr/local/bin`.
 ### Try using `which munin-node` `which munin-cgi-graph` `which munin-cgi-html` and `which spawn-fcgi` to find the full path, or just use `munin-node` `munin-cgi-graph` `munin-cgi-html` and `spawn-fcgi` if it is in `$PATH`.
-bin=/usr/local/munin/sbin/munin-node
-cgiGraphBin=/usr/local/munin/lib/cgi/munin-cgi-graph
-cgiHtmlBin=/usr/local/munin/lib/cgi/munin-cgi-html
+prefix=/usr/local/munin
+node=$prefix/sbin/munin-node
+cgiGraph=$prefix/lib/cgi/munin-cgi-graph
+cgiHtml=$prefix/lib/cgi/munin-cgi-html
 spawnFcgi=/usr/bin/spawn-fcgi
-if [ ! -x "$bin" ] || [ ! -x "$cgiGraphBin" ] || [ ! -x "$cgiHtmlBin" ] || [ ! -x "$spawnFcgi" ]; then
-    echo -e "\033[1;31m[E]\033[0m  Can not find $bin $cgiGraphBin $cgiHtmlBin or $spawnFcgi, maybe the program isn't installed." >&2
+if [ ! -x "$node" ] || [ ! -x "$cgiGraph" ] || [ ! -x "$cgiHtml" ] || [ ! -x "$spawnFcgi" ]; then
+    echo -e "\033[1;31m[E]\033[0m  Can not find $node $cgiGraph $cgiHtml or $spawnFcgi, maybe the program isn't installed." >&2
     exit 5
 fi
 
@@ -42,12 +43,14 @@ if [ ! -r "$config" ]; then
 fi
 
 ### By default, the pid file of program is in `/var/run`. So you don't need to edit this variable.
-pidFile=/var/run/munin/munin-node.pid
-cgiGraphPidFile=/var/run/munin/munin-cgi-graph.pid
-cgiHtmlPidFile=/var/run/munin/munin-cgi-html.pid
+pidDir=/var/run/munin
+nodePidFile=$pidDir/munin-node.pid
+cgiGraphPidFile=$pidDir/munin-cgi-graph.pid
+cgiHtmlPidFile=$pidDir/munin-cgi-html.pid
 
-cgiGraphSocketFile=/tmp/munin/munin-cgi-graph.sock
-cgiHtmlSocketFile=/tmp/munin/munin-cgi-html.sock
+socketDir=/tmp/munin
+cgiGraphSocketFile=$socketDir/munin-cgi-graph.sock
+cgiHtmlSocketFile=$socketDir/munin-cgi-html.sock
 
 cgiForkChildrenNum=3
 
@@ -58,16 +61,20 @@ script=$(basename "$0")
 
 getPid() {
     ### Delete spaces, tabs and newlines.
-    pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
+    nodePid=$(cat $nodePidFile 2>/dev/null | tr -d ' \t\n')
 
-    ### `$pidFile` may be blank. If the process exists, `! kill -0 $pid 2>/dev/null` will return 1.
-    if [ -z $pid ] || ! kill -0 $pid 2>/dev/null; then
-        rm -f $pidFile
-        unset pid
+    ### `$nodePidFile` may be blank. If the process exists, `! kill -0 $nodePid 2>/dev/null` will return 1.
+    if [ -z $nodePid ] || ! kill -0 $nodePid 2>/dev/null; then
+        rm -f $nodePidFile
+        unset nodePid
     fi
 
+    unset cgiHtmlPids cgiGraphPids
+
     i=0
-    awk 1 $cgiGraphPidFile 2>/dev/null | while read line; do
+    while read line; do
+        line=$(echo -n "$line" | tr -d ' \t\n')
+
         if [ -z $line ] || ! kill -0 $line 2>/dev/null; then
             continue
         fi
@@ -75,14 +82,16 @@ getPid() {
         cgiGraphPids[$i]=$line
 
         (( i++ ))
-    done
+    done < <(awk 1 $cgiGraphPidFile 2>/dev/null)
 
-    if [ ${#cg12iGraphPid[*]} -eq 0 ]; then
+    if [ ${#cgiGraphPids[*]} -eq 0 ]; then
         rm -f $cgiGraphPidFile
     fi
 
     i=0
-    awk 1 $cgiHtmlPidFile | while read line; do
+    while read line; do
+        line=$(echo -n "$line" | tr -d ' \t\n')
+
         if [ -z $line ] || ! kill -0 $line 2>/dev/null; then
             continue
         fi
@@ -90,7 +99,7 @@ getPid() {
         cgiHtmlPids[$i]=$line
 
         (( i++ ))
-    done
+    done < <(awk 1 $cgiHtmlPidFile 2>/dev/null)
 
     if [ ${#cgiHtmlPids[*]} -eq 0 ]; then
         rm -f $cgiHtmlPidFile
@@ -100,11 +109,29 @@ getPid() {
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
 
-    if ! $bin --config "$config" || \
-        ### WARNING: You can't specify a config file for munin-cgi. You must install munin from source if you want to use a custom config file.
-        ! $spawnFcgi -F $cgiForkChildrenNum -s $cgiGraphSocketFile -u munin -g munin -U munin -G munin -P $cgiGraphPidFile $cgiGraphBin || \
-        ! $spawnFcgi -F $cgiForkChildrenNum -s $cgiHtmlSocketFile -u munin -g munin -U munin -G munin -P $cgiHtmlPidFile $cgiHtmlBin; then
-        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
+    if [ ! -d "$pidDir" ]; then
+        mkdir -p $pidDir
+        chown -R munin:munin $pidDir
+    fi
+
+    if [ ! -d "$socketDir" ]; then
+        mkdir -p $socketDir
+        chown -R munin:munin $socketDir
+    fi
+
+    if ! $node --config "$config"; then
+        echo -e "\n\033[1;31m[E]\033[0m  Start munin-node error."
+        exit 1
+    fi
+
+    ### WARNING: You can't specify a config file for munin-cgi. You must install munin from source if you want to use a custom config file.
+    if ! $spawnFcgi -F $cgiForkChildrenNum -s $cgiGraphSocketFile -u munin -g munin -U munin -G munin -P $cgiGraphPidFile $cgiGraph; then
+        echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-graph error."
+        exit 1
+    fi
+
+    if ! $spawnFcgi -F $cgiForkChildrenNum -s $cgiHtmlSocketFile -u munin -g munin -U munin -G munin -P $cgiHtmlPidFile $cgiHtml; then
+        echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-html error."
         exit 1
     fi
 
@@ -113,9 +140,13 @@ doStart() {
 
     ### Successfully start the program if the process exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
-        if ! kill -0 $pid 2>/dev/null; then
+        if ! kill -0 $nodePid 2>/dev/null; then
             echo -e "\n\033[1;31m[E]\033[0m  Start munin-node failed."
             exit 1
+        fi
+
+        if [ ${#cgiGraphPids[*]} -eq 0 ]; then
+            echo -e "\n\033[1;33m[W]\033[0m  Start munin-cgi-graph failed."
         fi
 
         for cgiGraphPid in ${cgiGraphPids[*]}; do
@@ -124,6 +155,10 @@ doStart() {
                 exit 1
             fi
         done
+
+        if [ ${#cgiHtmlPids[*]} -eq 0 ]; then
+            echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-html failed."
+        fi
 
         for cgiHtmlPid in ${cgiHtmlPids[*]}; do
             if ! kill -0 $cgiHtmlPid 2>/dev/null; then
@@ -141,30 +176,33 @@ doStart() {
 
 doStop() {
     echo -en "\033[1;36m[I]\033[0m  Stopping $name"
-    if ! kill $pid 2>/dev/null; then
-        echo -e "\n\033[1;31m[E]\033[0m  Stop munin-node error."
+    if ! kill $nodePid 2>/dev/null; then
+        echo -e "\n\033[1;31m[E]\033[0m  Stop munin-node error. Try using $script kill."
         exit 1
     fi
 
     for cgiGraphPid in ${cgiGraphPids[*]}; do
         if ! kill $cgiGraphPid; then
-            echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-graph error."
+            echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-graph error. Try using $script kill."
             exit 1
         fi
     done
 
     for cgiHtmlPid in ${cgiHtmlPids[*]}; do
         if ! kill $cgiHtmlPid; then
-            echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-html error."
+            echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-html error. Try using $script kill."
             exit 1
         fi
     done
 
     ### Successfully stop the program if the process doesn't exists in 10 seconds.
     for (( i=0; i<=11; i++ )); do
-        if kill -0 $pid 2>/dev/null; then
+        echo -n '.'
+        sleep 1
+
+        if kill -0 $nodePid 2>/dev/null; then
             if [ $i -ge 10 ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop munin-node failed."
+                echo -e "\n\033[1;31m[E]\033[0m  Stop munin-node failed. Try using $script kill."
                 exit 1
             fi
 
@@ -174,7 +212,7 @@ doStop() {
         for cgiGraphPid in ${cgiGraphPids[*]}; do
             if kill -0 $cgiGraphPid 2>/dev/null; then
                 if [ $i -ge 10 ]; then
-                    echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-graph failed."
+                    echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-graph failed. Try using $script kill."
                     exit 1
                 fi
 
@@ -185,7 +223,7 @@ doStop() {
         for cgiHtmlPid in ${cgiHtmlPids[*]}; do
             if kill -0 $cgiHtmlPid 2>/dev/null; then
                 if [ $i -ge 10 ]; then
-                    echo -e "\n\033[1;31m[E]\033[0m  Stop munin-html-graph failed."
+                    echo -e "\n\033[1;31m[E]\033[0m  Stop munin-html-graph failed. Try using $script kill."
                     exit 1
                 fi
 
@@ -201,19 +239,19 @@ doStop() {
 case "$1" in
     start)
     getPid
-    if [ $pid ] || [ ${#cgiHtmlPids[*]} -gt 0 ] || [ ${#cgiGraphPids[*]} -gt 0 ]; then
+    if [ $nodePid ] || [ ${#cgiGraphPids[*]} -gt 0 ] || [ ${#cgiHtmlPids[*]} -gt 0 ]; then
         echo -e "\033[1;33m[W]\033[0m  $name is already running:"
 
-        if [ $pid ]; then
-            echo -e "\033[1;33m[W]\033[0m  munin-node pid = $pid"
+        if [ $nodePid ]; then
+            echo -e "\033[1;33m[W]\033[0m  munin-node pid = $nodePid."
         fi
 
         if [ ${#cgiGraphPids[*]} -gt 0 ]; then
-            echo -e "\033[1;33m[W]\033[0m  munin-cgi-graph pids are ${cgiGraphPids[*]}"
+            echo -e "\033[1;33m[W]\033[0m  munin-cgi-graph pids are ${cgiGraphPids[*]}."
         fi
 
         if [ ${#cgiHtmlPids[*]} -gt 0 ]; then
-            echo -e "\033[1;33m[W]\033[0m  munin-cgi-html pids are ${cgiHtmlPids[*]}"
+            echo -e "\033[1;33m[W]\033[0m  munin-cgi-html pids are ${cgiHtmlPids[*]}."
         fi
     fi
 
@@ -222,7 +260,7 @@ case "$1" in
 
     stop)
     getPid
-    if [ -z $pid ] && [ ${#cgiHtmlPids[*]} -eq 0 ] && [ ${#cgiGraphPids[*]} -eq 0 ]; then
+    if [ -z $nodePid ] && [ ${#cgiGraphPids[*]} -eq 0 ] && [ ${#cgiHtmlPids[*]} -eq 0 ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 0
     fi
@@ -232,22 +270,22 @@ case "$1" in
 
     kill)
     getPid
-    if [ -z $pid ] && [ ${#cgiHtmlPids[*]} -eq 0 ] && [ ${#cgiGraphPids[*]} -eq 0 ]; then
+    if [ -z $nodePid ] && [ ${#cgiGraphPids[*]} -eq 0 ] && [ ${#cgiHtmlPids[*]} -eq 0 ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 0
     fi
 
     echo -e "\033[1;36m[I]\033[0m  Forcefully killing the process of $name..."
 
-    if ! kill -9 $pid 2>/dev/null; then
-        echo -e "\n\033[1;31m[E]\033[0m  Start munin-node failed."
+    if ! kill -9 $nodePid 2>/dev/null; then
+        echo -e "\033[1;31m[E]\033[0m  Kill munin-node failed."
         exit 1
     fi
-    rm -f $pidFile
+    rm -f $nodePidFile
 
     for cgiGraphPid in ${cgiGraphPids[*]}; do
         if ! kill -9 $cgiGraphPid 2>/dev/null; then
-            echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-graph failed."
+            echo -e "\033[1;31m[E]\033[0m  Kill munin-cgi-graph failed."
             exit 1
         fi
     done
@@ -255,7 +293,7 @@ case "$1" in
 
     for cgiHtmlPid in ${cgiHtmlPids[*]}; do
         if ! kill -9 $cgiHtmlPid 2>/dev/null; then
-            echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-html failed."
+            echo -e "\033[1;31m[E]\033[0m  Kill munin-cgi-html failed."
             exit 1
         fi
     done
@@ -266,8 +304,8 @@ case "$1" in
 
     restart)
     getPid
-    if [ -z $pid ]; then
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
+    if [ -z $nodePid ]; then
+        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
 
         doStart
         exit 0
@@ -281,8 +319,8 @@ case "$1" in
 
     force-reload)
     getPid
-    if [ -z $pid ]; then
-        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
+    if [ -z $nodePid ]; then
+        echo -e "\033[1;31m[E]\033[0m  $name isn't running."
         exit 7
     fi
 
@@ -293,29 +331,29 @@ case "$1" in
 
     status)
     getPid
-    if [ -z $pid ] && [ ${#cgiHtmlPids[*]} -eq 0 ] && [ ${#cgiGraphPids[*]} -eq 0 ]; then
+    if [ -z $nodePid ] && [ ${#cgiGraphPids[*]} -eq 0 ] && [ ${#cgiHtmlPids[*]} -eq 0 ]; then
         echo -e "\033[1;32m[N]\033[0m  $name isn't running."
         exit 3
     fi
 
-    echo -e "\033[1;33m[W]\033[0m  $name is already running:"
+    echo -e "\033[1;32m[N]\033[0m  $name is already running:"
 
-    if [ $pid ]; then
-        echo -e "\033[1;33m[W]\033[0m  munin-node pid = $pid"
+    if [ $nodePid ]; then
+        echo -e "\033[1;32m[N]\033[0m  munin-node pid = $nodePid."
     fi
 
     if [ ${#cgiGraphPids[*]} -gt 0 ]; then
-        echo -e "\033[1;33m[W]\033[0m  munin-cgi-graph pids are ${cgiGraphPids[*]}"
+        echo -e "\033[1;32m[N]\033[0m  munin-cgi-graph pids are ${cgiGraphPids[*]}."
     fi
 
     if [ ${#cgiHtmlPids[*]} -gt 0 ]; then
-        echo -e "\033[1;33m[W]\033[0m  munin-cgi-html pids are ${cgiHtmlPids[*]}"
+        echo -e "\033[1;32m[N]\033[0m  munin-cgi-html pids are ${cgiHtmlPids[*]}."
     fi
     ;;
 
     *)
     ### You can't reload the configuration file in here.
-#   echo "Usage: [sudo] $script {start|stop|kill|restart|force-reload|reload|status}" >&2
+#   echo "Usage: [sudo] $script {start|stop|kill|restart|force-reload|reload|status}." >&2
     echo "Usage: [sudo] $script {start|stop|kill|restart|force-reload|status}." >&2
     exit 3
     ;;
