update

diff --git a/munin-server b/munin-server
--- a/munin-server
+++ b/munin-server
@@ -24,14 +24,13 @@ name=munin
 ########## Maybe you need to modify these variables. ##########
 
 ### In the most cases, the binary file of program is in `/usr/bin` or `/usr/local/bin`.
-### Try using `which munin-node` `which munin-cgi-graph` `which munin-cgi-html` and `which spawn-fcgi` to find the full path, or just use `munin-node` `munin-cgi-graph` `munin-cgi-html` and `spawn-fcgi` if it is in `$PATH`.
+### Try using `which munin-node` `which spawn-fcgi` and `which fcgiwrap` to find the full path, or just use `munin-node` `spawn-fcgi` and `fcgiwrap` if it is in `$PATH`.
 prefix=/usr/local/munin
 node=$prefix/sbin/munin-node
-cgiGraph=$prefix/lib/cgi/munin-cgi-graph
-cgiHtml=$prefix/lib/cgi/munin-cgi-html
 spawnFcgi=/usr/bin/spawn-fcgi
-if [ ! -x "$node" ] || [ ! -x "$cgiGraph" ] || [ ! -x "$cgiHtml" ] || [ ! -x "$spawnFcgi" ]; then
-    echo -e "\033[1;31m[E]\033[0m  Can not find $node $cgiGraph $cgiHtml or $spawnFcgi, maybe the program isn't installed." >&2
+fcgiwrap=/usr/sbin/fcgiwrap
+if [ ! -x "$node" ] || [ ! -x "$spawnFcgi" ] || [ ! -x "$fcgiwrap" ]; then
+    echo -e "\033[1;31m[E]\033[0m  Can not find $node $spawnFcgi or $fcgiwrap, maybe the program isn't installed." >&2
     exit 5
 fi
 
@@ -45,13 +44,9 @@ fi
 ### By default, the pid file of program is in `/var/run`. So you don't need to edit this variable.
 pidDir=/var/run/munin
 nodePidFile=$pidDir/munin-node.pid
-cgiGraphPidFile=$pidDir/munin-cgi-graph.pid
-cgiHtmlPidFile=$pidDir/munin-cgi-html.pid
+cgiPidFile=$pidDir/munin-cgi.pid
 
-socketDir=/tmp/munin
-cgiGraphSocketFile=$socketDir/munin-cgi-graph.sock
-cgiHtmlSocketFile=$socketDir/munin-cgi-html.sock
-
+cgiSocketFile=/tmp/munin-cgi.sock
 cgiForkChildrenNum=3
 
 ##########                                           ##########
@@ -69,7 +64,7 @@ getPid() {
         unset nodePid
     fi
 
-    unset cgiHtmlPids cgiGraphPids
+    unset cgiPids
 
     i=0
     while read line; do
@@ -79,30 +74,13 @@ getPid() {
             continue
         fi
 
-        cgiGraphPids[$i]=$line
+        cgiPids[$i]=$line
 
         (( i++ ))
-    done < <(awk 1 $cgiGraphPidFile 2>/dev/null)
+    done < <(awk 1 $cgiPidFile 2>/dev/null)
 
-    if [ ${#cgiGraphPids[*]} -eq 0 ]; then
-        rm -f $cgiGraphPidFile
-    fi
-
-    i=0
-    while read line; do
-        line=$(echo -n "$line" | tr -d ' \t\n')
-
-        if [ -z $line ] || ! kill -0 $line 2>/dev/null; then
-            continue
-        fi
-
-        cgiHtmlPids[$i]=$line
-
-        (( i++ ))
-    done < <(awk 1 $cgiHtmlPidFile 2>/dev/null)
-
-    if [ ${#cgiHtmlPids[*]} -eq 0 ]; then
-        rm -f $cgiHtmlPidFile
+    if [ ${#cgiPids[*]} -eq 0 ]; then
+        rm -f $cgiPidFile
     fi
 }
 
@@ -114,28 +92,17 @@ doStart() {
         chown -R munin:munin $pidDir
     fi
 
-    if [ ! -d "$socketDir" ]; then
-        mkdir -p $socketDir
-        chown -R munin:munin $socketDir
-    fi
-
     if ! $node --config "$config"; then
         echo -e "\n\033[1;31m[E]\033[0m  Start munin-node error."
         exit 1
     fi
 
     ### WARNING: You can't specify a config file for munin-cgi. You must install munin from source if you want to use a custom config file.
-    if ! $spawnFcgi -F $cgiForkChildrenNum -s $cgiGraphSocketFile -u munin -g munin -U munin -G munin -P $cgiGraphPidFile $cgiGraph; then
-        echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-graph error."
+    if ! $spawnFcgi -F $cgiForkChildrenNum -s $cgiSocketFile -u munin -g munin -U munin -G munin -P $cgiPidFile -- $fcgiwrap -f; then
+        echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi error."
         exit 1
     fi
-    chmod 666 $cgiGraphSocketFile
-
-    if ! $spawnFcgi -F $cgiForkChildrenNum -s $cgiHtmlSocketFile -u munin -g munin -U munin -G munin -P $cgiHtmlPidFile $cgiHtml; then
-        echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-html error."
-        exit 1
-    fi
-    chmod 666 $cgiHtmlSocketFile
+    chmod 666 $cgiSocketFile
 
     getPid
 
@@ -146,24 +113,13 @@ doStart() {
             exit 1
         fi
 
-        if [ ${#cgiGraphPids[*]} -eq 0 ]; then
-            echo -e "\n\033[1;33m[W]\033[0m  Start munin-cgi-graph failed."
+        if [ ${#cgiPids[*]} -eq 0 ]; then
+            echo -e "\n\033[1;33m[W]\033[0m  Start munin-cgi failed."
         fi
 
-        for cgiGraphPid in ${cgiGraphPids[*]}; do
-            if ! kill -0 $cgiGraphPid 2>/dev/null; then
-                echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-graph failed."
-                exit 1
-            fi
-        done
-
-        if [ ${#cgiHtmlPids[*]} -eq 0 ]; then
-            echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-html failed."
-        fi
-
-        for cgiHtmlPid in ${cgiHtmlPids[*]}; do
-            if ! kill -0 $cgiHtmlPid 2>/dev/null; then
-                echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-html failed."
+        for cgiPid in ${cgiPids[*]}; do
+            if ! kill -0 $cgiPid 2>/dev/null; then
+                echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi failed."
                 exit 1
             fi
         done
@@ -183,16 +139,9 @@ doStop() {
         exit 1
     fi
 
-    for cgiGraphPid in ${cgiGraphPids[*]}; do
-        if ! kill $cgiGraphPid; then
-            echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-graph error. Try using $script kill."
-            exit 1
-        fi
-    done
-
-    for cgiHtmlPid in ${cgiHtmlPids[*]}; do
-        if ! kill $cgiHtmlPid; then
-            echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-html error. Try using $script kill."
+    for cgiPid in ${cgiPids[*]}; do
+        if ! kill $cgiPid; then
+            echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi error. Try using $script kill."
             exit 1
         fi
     done
@@ -211,21 +160,10 @@ doStop() {
             continue
         fi
 
-        for cgiGraphPid in ${cgiGraphPids[*]}; do
-            if kill -0 $cgiGraphPid 2>/dev/null; then
+        for cgiPid in ${cgiPids[*]}; do
+            if kill -0 $cgiPid 2>/dev/null; then
                 if [ $i -ge 10 ]; then
-                    echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-graph failed. Try using $script kill."
-                    exit 1
-                fi
-
-                continue
-            fi
-        done
-
-        for cgiHtmlPid in ${cgiHtmlPids[*]}; do
-            if kill -0 $cgiHtmlPid 2>/dev/null; then
-                if [ $i -ge 10 ]; then
-                    echo -e "\n\033[1;31m[E]\033[0m  Stop munin-html-graph failed. Try using $script kill."
+                    echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi failed. Try using $script kill."
                     exit 1
                 fi
 
@@ -241,19 +179,15 @@ doStop() {
 case "$1" in
     start)
     getPid
-    if [ $nodePid ] || [ ${#cgiGraphPids[*]} -gt 0 ] || [ ${#cgiHtmlPids[*]} -gt 0 ]; then
+    if [ $nodePid ] || [ ${#cgiPids[*]} -gt 0 ]; then
         echo -e "\033[1;33m[W]\033[0m  $name is already running:"
 
         if [ $nodePid ]; then
             echo -e "\033[1;33m[W]\033[0m  munin-node pid = $nodePid."
         fi
 
-        if [ ${#cgiGraphPids[*]} -gt 0 ]; then
-            echo -e "\033[1;33m[W]\033[0m  munin-cgi-graph pids are ${cgiGraphPids[*]}."
-        fi
-
-        if [ ${#cgiHtmlPids[*]} -gt 0 ]; then
-            echo -e "\033[1;33m[W]\033[0m  munin-cgi-html pids are ${cgiHtmlPids[*]}."
+        if [ ${#cgiPids[*]} -gt 0 ]; then
+            echo -e "\033[1;33m[W]\033[0m  munin-cgi pids are ${cgiPids[*]}."
         fi
 
         exit 0
@@ -264,7 +198,7 @@ case "$1" in
 
     stop)
     getPid
-    if [ -z $nodePid ] && [ ${#cgiGraphPids[*]} -eq 0 ] && [ ${#cgiHtmlPids[*]} -eq 0 ]; then
+    if [ -z $nodePid ] && [ ${#cgiPids[*]} -eq 0 ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 0
     fi
@@ -274,7 +208,7 @@ case "$1" in
 
     kill)
     getPid
-    if [ -z $nodePid ] && [ ${#cgiGraphPids[*]} -eq 0 ] && [ ${#cgiHtmlPids[*]} -eq 0 ]; then
+    if [ -z $nodePid ] && [ ${#cgiPids[*]} -eq 0 ]; then
         echo -e "\033[1;33m[W]\033[0m  $name isn't running."
         exit 0
     fi
@@ -287,21 +221,13 @@ case "$1" in
     fi
     rm -f $nodePidFile
 
-    for cgiGraphPid in ${cgiGraphPids[*]}; do
-        if ! kill -9 $cgiGraphPid 2>/dev/null; then
-            echo -e "\033[1;31m[E]\033[0m  Kill munin-cgi-graph failed."
+    for cgiPid in ${cgiPids[*]}; do
+        if ! kill -9 $cgiPid 2>/dev/null; then
+            echo -e "\033[1;31m[E]\033[0m  Kill munin-cgi failed."
             exit 1
         fi
     done
-    rm -f $cgiGraphPidFile
-
-    for cgiHtmlPid in ${cgiHtmlPids[*]}; do
-        if ! kill -9 $cgiHtmlPid 2>/dev/null; then
-            echo -e "\033[1;31m[E]\033[0m  Kill munin-cgi-html failed."
-            exit 1
-        fi
-    done
-    rm -f $cgiHtmlPidFile
+    rm -f $cgiPidFile
 
     echo -e "\033[1;32m[N]\033[0m  Kill $name done."
     ;;
@@ -333,7 +259,7 @@ case "$1" in
 
     status)
     getPid
-    if [ -z $nodePid ] && [ ${#cgiGraphPids[*]} -eq 0 ] && [ ${#cgiHtmlPids[*]} -eq 0 ]; then
+    if [ -z $nodePid ] && [ ${#cgiPids[*]} -eq 0 ]; then
         echo -e "\033[1;32m[N]\033[0m  $name isn't running."
         exit 3
     fi
@@ -344,13 +270,10 @@ case "$1" in
         echo -e "\033[1;32m[N]\033[0m  munin-node pid = $nodePid."
     fi
 
-    if [ ${#cgiGraphPids[*]} -gt 0 ]; then
-        echo -e "\033[1;32m[N]\033[0m  munin-cgi-graph pids are ${cgiGraphPids[*]}."
+    if [ ${#cgiPids[*]} -gt 0 ]; then
+        echo -e "\033[1;32m[N]\033[0m  munin-cgi pids are ${cgiPids[*]}."
     fi
 
-    if [ ${#cgiHtmlPids[*]} -gt 0 ]; then
-        echo -e "\033[1;32m[N]\033[0m  munin-cgi-html pids are ${cgiHtmlPids[*]}."
-    fi
     ;;
 
     *)
