add redis

diff --git a/redis b/redis
--- a/redis
+++ b/redis
@@ -1,15 +1,15 @@
-#! /bin/sh
+#! /bin/bash
 
 ### BEGIN INIT INFO
-# Provides:          php-fpm
+# Provides:          redis
 # Required-Start:    $local_fs $network $named $remote_fs $syslog
 # Required-Stop:     $local_fs $network $named $remote_fs $syslog
 # Should-Start:      $network $named
 # Should-Stop:       $network $named
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: php-fpm daemon
-# Description:       PHP-FPM (FastCGI Process Manager) is an alternative PHP FastCGI implementation with some additional features useful for sites of any size, especially busier sites.
+# Short-Description: redis daemon
+# Description:       Redis is an open-source, networked, in-memory, key-value data store with optional durability.
 ### END INIT INFO
 
 PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:~/bin
@@ -21,15 +21,18 @@ if [ "$(id -u)" != "0" ]; then
 fi
 
 ### Maybe you need to modify these variables.
-name=php-fpm
+name=redis
 ### In the most cases, the binary file of programs are in `/usr/bin` or `/usr/local/bin`.
-### Try use `which $name` to find the full path, or just use `$name` if it is in `$PATH`.
-bin=/usr/local/php/sbin/$name
+### Try use `which redis-server` and `which redis-cli` to find the full path, or just use `redis-server` and `redis-cli` if it is in `$PATH`.
+bin=/usr/local/redis/bin/redis-server
+cliBin=/usr/local/redis/bin/redis-cli
 ### In the most cases, the configuration file of programs are in `/etc`. You can create your own configuration file and edit this variable to the new path.
-config=/home/www/etc/php/$name.conf
-ini=/home/www/etc/php/php.ini
-### By default, the pid file of programs are in `/var/run`. So you don't need to edit this variable. You can find the path in the configuration file.
+config=/home/www/etc/$name.conf
+### By default, the pid file of programs are in `/var/run`. So you don't need to edit this variable.
+### But pay attention to `$name`, it may be different. You can find the path in the configuration file.
 pidFile=/var/run/$name.pid
+### By default, the port is 6379. So you don't need to edit this variable. And you can find it in the configuration file.
+port=6379
 
 script=$(basename "$0")
 
@@ -45,15 +48,22 @@ getPid() {
 
 doStart() {
     echo -en "\033[1;36m[I]\033[0m  Starting $name"
-    ### Block zend version notice.
-    if $bin -c "$ini" -y "$config" > /dev/null 2>&1; then
+    ### I don't want it to run as root. But the program may be doesn't have permission to create the log file or the database directory.
+    ### So you need to create them manually, and modify owner & group. You can find the paths in the configuration file.
+    if su redis -s /bin/bash -c "$bin '$config'"; then
         echo -n '.'
-        getPid
     else
         echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
         exit 1
     fi
 
+    ### Wait for redis-server start. Try waiting for a longer time if start redis-server failed.
+    for (( i=0; i<=1; i++ )); do
+        echo -n '.'
+        sleep 1
+    done
+
+    getPid
     ### Successfully start the application if the progress exists after 5 seconds.
     for (( i=0; i<=5; i++ )); do
         if kill -0 $pid 2>/dev/null; then
@@ -68,11 +78,11 @@ doStart() {
 }
 
 doStop() {
-    echo -en "\033[1;36m[I]\033[0m  Gracefully stopping $name"
-    if kill -QUIT $pid; then
+    echo -en "\033[1;36m[I]\033[0m  Stopping $name"
+    if $cliBin -p $port shutdown; then
         echo -n '.'
     else
-        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error. Try using $script kill."
+        echo -e "\n\033[1;31m[E]\033[0m  Stop $name error."
         exit 1
     fi
 
@@ -80,7 +90,7 @@ doStop() {
     for (( i=0; i<=10; i++ )); do
         if kill -0 $pid 2>/dev/null; then
             if [ "$i" = "10" ]; then
-                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $script kill."
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed."
                 exit 1
             fi
             echo -n '.'
@@ -115,40 +125,6 @@ case "$1" in
     fi
     ;;
 
-    kill)
-    getPid
-    if [ "$pid" ]; then
-        echo -e "\033[1;36m[I]\033[0m  Fast shutdown $name..."
-
-        if kill -TERM $pid; then
-            echo -e "\033[1;32m[N]\033[0m  Shutdown $name done."
-        else
-            echo -e "\033[1;31m[E]\033[0m  Shutdown $name error."
-            exit 1
-        fi
-    else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
-        exit 2
-    fi
-    ;;
-
-    reload)
-    getPid
-    if [ "$pid" ]; then
-        echo -e "\033[1;36m[I]\033[0m  Reloading $name configuration file..."
-
-        if kill -USR2 $pid; then
-            echo -e "\033[1;32m[N]\033[0m  Reload $name done."
-        else
-            echo -e "\033[1;31m[E]\033[0m  Reload $name error."
-            exit 1
-        fi
-    else
-        echo -e "\033[1;33m[W]\033[0m  $name isn't running"
-        doStart
-    fi
-    ;;
-
     restart)
     getPid
     if [ "$pid" ]; then
@@ -171,7 +147,12 @@ case "$1" in
     ;;
 
     *)
-    echo "Usage: [sudo] $script {start|stop|kill|reload|restart|status}." >&2
+    ### You can't reload the configuration file in here,
+    ### but you can use the `CONFIG SET` command which is used in order to reconfigure the server at run time without the need to restart Redis.
+    ### See http://redis.io/commands/config-set.
+    ### You also can't forcefully kill redis-server, it's not safe.
+#   echo "Usage: [sudo] $script {start|stop|kill|restart|reload|status}" >&2
+    echo "Usage: [sudo] $script {start|stop|restart|status}." >&2
     exit 3
     ;;
 esac
