update

diff --git a/sslocal b/sslocal
--- a/sslocal
+++ b/sslocal
@@ -12,84 +12,109 @@
 # Description: shadowsocks client daemon
 ### END INIT INFO
 
-bin=/usr/local/bin/sslocal
+name=sslocal
+bin=/usr/local/bin/$name
 config=/etc/shadowsocks.json
 log=/var/log/shadowsocks.log
-pidFile=/var/run/sslocal.pid
+pidFile=/var/run/$name.pid
+
 if [ -f "$pidFile" ]; then
     pid=$(cat $pidFile)
-    checkProgress=$(kill -0 $pid 2>&1 > /dev/null && echo -n $?)
-    if [ "$checkProgress" != "0" ]; then
+    if [ ! -d "/proc/$pid" ]; then
         rm -f $pidFile
         unset pid
     fi
 fi
-script=/etc/init.d/sslocal
 
-shadowsocks() {
-    nohup $bin -c "$config" >> "$log" 2>&1 & echo -n $! > $pidFile
-}
-
+### Successfully start the application if the progress exists after 3 seconds.
 doStart() {
-    if [ "$pid" ]; then
-        echo "shadowsocks already running. pid = $pid"
-    else
-        shadowsocks
-        echo 'Done.'
-    fi
+    echo -en "\033[1;36m[I]\033[0m  Starting $name"
+    nohup $bin -c "$config" >> "$log" 2>&1 & echo -n $! > $pidFile
+    pid=$!
+    for (( i=0; i<=3; i++ )); do
+        if [ -d "/proc/$pid" ]; then
+            echo -n '.'
+            sleep 1
+        else
+            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
+            exit 1
+        fi
+    done
+    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
 }
 
+### Successfully stop the application if the progress doesn't exists in 10 seconds.
 doStop() {
-    if [ "$pid" ]; then
-        kill $pid
-        rm -f $pidFile
-        echo 'Done.'
-    else
-        echo 'shadowsocks not running.'
-    fi
-}
-
-doRestart() {
-    if [ "$pid" ]; then
-        echo 'Stopping shadowsocks...'
-        kill $pid
-        rm -f $pidFile
-        echo -e 'Done.\nStarting shadowsocks...'
-        shadowsocks
-        echo 'Done.'
-    else
-        echo -e 'shadowsocks not running.\nStarting shadowsocks...'
-        shadowsocks
-        echo 'Done.'
-    fi
-}
-
-checkStatus() {
-    if [ "$pid" ]; then
-        echo "shadowsocks is running. pid = $pid"
-    else
-        echo 'shadowsocks not running.'
-    fi
+    echo -en "\033[1;36m[I]\033[0m  Stopping $name"
+    kill $pid
+    for (( i=0; i<=10; i++ )); do
+        if [ -d "/proc/$pid" ]; then
+            if [ "$i" = "10" ]; then
+                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
+                exit 1
+            fi
+            echo -n '.'
+            sleep 1
+        else
+            rm -f $pidFile
+            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
+            break
+        fi
+    done
 }
 
 case "$1" in
     start)
-    echo 'Starting shadowsocks...'
-    doStart
+    if [ "$pid" ]; then
+        echo -e "\033[1;33m[W]\033[0m  $name already running. pid = $pid"
+        exit 2
+    else
+        doStart
+    fi
     ;;
+
     stop)
-    echo 'Stopping shadowsocks...'
-    doStop
+    if [ "$pid" ]; then
+        doStop
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
     ;;
+
+    kill)
+    if [ "$pid" ]; then
+        echo -e "\033[1;36m[I]\033[0m  Force killing the progress of $name..."
+        kill -9 $pid
+        rm -f $pidFile
+        echo -e "\033[1;32m[N]\033[0m  Kill $name Done."
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running."
+        exit 2
+    fi
+    ;;
+
     restart)
-    echo 'Restarting shadowsocks: '
-    doRestart
+    echo -e "\033[1;36m[I]\033[0m  Restarting $name: "
+    if [ "$pid" ]; then
+        doStop
+        doStart
+    else
+        echo -e "\033[1;33m[W]\033[0m  $name not running"
+        doStart
+    fi
     ;;
+
     status)
-    checkStatus
+    if [ "$pid" ]; then
+        echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
+    else
+        echo -e "\033[1;32m[N]\033[0m  $name not running."
+    fi
     ;;
+
     *)
-    echo "Usage: $script {start|stop|restart|status}" >&2
+    echo "Usage: $0 {start|stop|kill|restart|status}." >&2
     exit 3
     ;;
 esac
